module Network.WebSockets.Connection.AsWs
  ( module Network.WebSockets.Connection.AsWs
  ) where
-- generated by https://github.com/rvion/ride/tree/master/jetpack-gen

import qualified Network.WebSockets.Connection as I


-- ws_sendCloseCode :: forall a. WebSocketsData a => Connection -> Word16 -> a -> IO ()
ws_sendCloseCode = I.sendCloseCode
