{-# LANGUAGE NoMonomorphismRestriction #-}
module Data.Conduit.Binary.AsCb where
-- generated by rvion/jetpack-gen 

import Data.Conduit.Binary as I

-- ($s$fOrdPtr_$c>=) doesn't seem to be exported
-- ($wa) doesn't seem to be exported
-- ($wa1) doesn't seem to be exported
-- ($wa2) doesn't seem to be exported
-- ($wa3) doesn't seem to be exported
-- ($wtake) doesn't seem to be exported

cb_conduitFile =  I.conduitFile
-- (conduitFile1) doesn't seem to be exported

cb_conduitHandle =  I.conduitHandle

cb_drop =  I.drop
-- (drop1) doesn't seem to be exported
-- (drop2) doesn't seem to be exported

cb_dropWhile =  I.dropWhile
-- (dropWhile1) doesn't seem to be exported

cb_head =  I.head
-- (head1) doesn't seem to be exported

cb_isolate =  I.isolate
-- (isolate1) doesn't seem to be exported

cb_lines =  I.lines

cb_mapM_ =  I.mapM_
-- (mapM_BS) doesn't seem to be exported

cb_sinkCacheLength =  I.sinkCacheLength

cb_sinkFile =  I.sinkFile

cb_sinkHandle =  I.sinkHandle

cb_sinkIOHandle =  I.sinkIOHandle
-- (sinkIOHandle1) doesn't seem to be exported

cb_sinkLbs =  I.sinkLbs
-- (sinkLbs1) doesn't seem to be exported
-- (sinkLbs2) doesn't seem to be exported
-- (sinkLbs3) doesn't seem to be exported

cb_sourceFile =  I.sourceFile

cb_sourceFileRange =  I.sourceFileRange

cb_sourceHandle =  I.sourceHandle

cb_sourceHandleRange =  I.sourceHandleRange

cb_sourceHandleRangeWithBuffer =  I.sourceHandleRangeWithBuffer

cb_sourceHandleUnsafe =  I.sourceHandleUnsafe

cb_sourceIOHandle =  I.sourceIOHandle

cb_sourceLbs =  I.sourceLbs

cb_take =  I.take
-- (take1) doesn't seem to be exported
-- (take2) doesn't seem to be exported

cb_takeWhile =  I.takeWhile
-- (takeWhile1) doesn't seem to be exported
