module Network.HTTP.Types.Status.AsWai
  ( module Network.HTTP.Types.Status.AsWai
  ) where
-- generated by https://github.com/rvion/ride/tree/master/jetpack-gen

import qualified Network.HTTP.Types.Status as I


-- wai_networkAuthenticationRequired511 :: Status
wai_networkAuthenticationRequired511 = I.networkAuthenticationRequired511

-- wai_preconditionRequired428 :: Status
wai_preconditionRequired428 = I.preconditionRequired428

-- wai_requestHeaderFieldsTooLarge431 :: Status
wai_requestHeaderFieldsTooLarge431 = I.requestHeaderFieldsTooLarge431

-- wai_status428 :: Status
wai_status428 = I.status428

-- wai_status429 :: Status
wai_status429 = I.status429

-- wai_status431 :: Status
wai_status431 = I.status431

-- wai_status511 :: Status
wai_status511 = I.status511

-- wai_tooManyRequests429 :: Status
wai_tooManyRequests429 = I.tooManyRequests429
