flags: {}
packages:
- '.'
- 'haskell-web-ide'
- 'jetpack'
- 'jetpack-gen'
- 'reexport-demo'
- 'lucid-forms'
- 'db-layer'
- 'dgx'
- 'chrotomate'
extra-deps:
- 'hashids-1.0.2.1'
resolver: nightly-2015-12-14
