flags: {}
packages:
# Libraries
- 'jetpack'
- 'reexport-demo'
- 'db-layer'
# Libraries + executables
- 'haskell-web-ide'
- 'jetpack-gen'
- 'web-playground'
- 'chrotomate'
extra-deps:
- 'hashids-1.0.2.1'
resolver: nightly-2015-12-14
