 -- generated by rvion/jetpack-gen 
module AsLt.hs where
import Data.Text.Lazy.IO


lt_appendFile :: FilePath -> Text -> IO ()
lt_appendFile =  T.appendFile
-- (appendFile1) doesn't seem to be exported
-- (appendFile2) doesn't seem to be exported

lt_getContents :: IO Text
lt_getContents =  T.getContents
-- (getContents1) doesn't seem to be exported
-- (getContents2) doesn't seem to be exported
-- (getContents3) doesn't seem to be exported
-- (getContents4) doesn't seem to be exported
-- (getContents5) doesn't seem to be exported
-- (getContents6) doesn't seem to be exported
-- (getContents7) doesn't seem to be exported

lt_getLine :: IO Text
lt_getLine =  T.getLine
-- (getLine1) doesn't seem to be exported

lt_hGetContents :: Handle -> IO Text
lt_hGetContents =  T.hGetContents

lt_hGetLine :: Handle -> IO Text
lt_hGetLine =  T.hGetLine
-- (hGetLine1) doesn't seem to be exported

lt_hPutStr :: Handle -> Text -> IO ()
lt_hPutStr =  T.hPutStr

lt_hPutStrLn :: Handle -> Text -> IO ()
lt_hPutStrLn =  T.hPutStrLn
-- (hPutStrLn1) doesn't seem to be exported

lt_interact :: (Text -> Text) -> IO ()
lt_interact =  T.interact
-- (interact1) doesn't seem to be exported

lt_putStr :: Text -> IO ()
lt_putStr =  T.putStr
-- (putStr1) doesn't seem to be exported

lt_putStrLn :: Text -> IO ()
lt_putStrLn =  T.putStrLn
-- (putStrLn1) doesn't seem to be exported

lt_readFile :: FilePath -> IO Text
lt_readFile =  T.readFile
-- (readFile1) doesn't seem to be exported

lt_writeFile :: FilePath -> Text -> IO ()
lt_writeFile =  T.writeFile
-- (writeFile1) doesn't seem to be exported
