{-# LANGUAGE NoMonomorphismRestriction #-}

module Data.Text.Lazy.IO.AsLt where
-- generated by rvion/jetpack-gen 

import Data.Text.Lazy.IO as I

lt_appendFile =  I.appendFile
lt_getContents =  I.getContents
lt_getLine =  I.getLine
lt_hGetContents =  I.hGetContents
lt_hGetLine =  I.hGetLine
lt_hPutStr =  I.hPutStr
lt_hPutStrLn =  I.hPutStrLn
lt_interact =  I.interact
lt_putStr =  I.putStr
lt_putStrLn =  I.putStrLn
lt_readFile =  I.readFile
lt_writeFile =  I.writeFile
