module Codec.Archive.Tar.Check.AsTar where
-- generated by rvion/jetpack-gen 

import Codec.Archive.Tar.Check as I

tar_checkPortability = I.checkPortability
tar_checkSecurity = I.checkSecurity
tar_checkTarbomb = I.checkTarbomb
type TarFileNameError  = I.FileNameError 
type TarPortabilityError  = I.PortabilityError 
type TarPortabilityPlatform  = I.PortabilityPlatform 
type TarTarBombError  = I.TarBombError 
