module Codec.Archive.Tar.Check.AsTar where
-- generated by https://github.com/rvion/ride/tree/master/jetpack-gen

import qualified Codec.Archive.Tar.Check as I

-- tar_checkPortability :: forall e. Entries e -> Entries (Either e PortabilityError)
tar_checkPortability = I.checkPortability

-- tar_checkSecurity :: forall e. Entries e -> Entries (Either e FileNameError)
tar_checkSecurity = I.checkSecurity

-- tar_checkTarbomb :: forall e. FilePath -> Entries e -> Entries (Either e TarBombError)
tar_checkTarbomb = I.checkTarbomb

type TarFileNameError  = I.FileNameError
tar__mkInvalidFileName =  I.InvalidFileName-- constructor
pattern TarInvalidFileName a <-  I.InvalidFileName a
tar__mkAbsoluteFileName =  I.AbsoluteFileName-- constructor
pattern TarAbsoluteFileName a <-  I.AbsoluteFileName a
type TarPortabilityError  = I.PortabilityError
tar__mkNonPortableFormat =  I.NonPortableFormat-- constructor
pattern TarNonPortableFormat a <-  I.NonPortableFormat a
tar__mkNonPortableFileType =  I.NonPortableFileType-- constructor
pattern TarNonPortableFileType  <-  I.NonPortableFileType 
tar__mkNonPortableEntryNameChar =  I.NonPortableEntryNameChar-- constructor
pattern TarNonPortableEntryNameChar a <-  I.NonPortableEntryNameChar a
tar__mkNonPortableFileName =  I.NonPortableFileName-- constructor
pattern TarNonPortableFileName a b <-  I.NonPortableFileName a b
type TarPortabilityPlatform  = I.PortabilityPlatform
type TarTarBombError  = I.TarBombError
tar__mkTarBombError =  I.TarBombError-- constructor
pattern TarTarBombError a <-  I.TarBombError a
