module Network.HTTP.Types.Header.AsWai
  ( module Network.HTTP.Types.Header.AsWai
  ) where
-- generated by https://github.com/rvion/ride/tree/master/jetpack-gen

import qualified Network.HTTP.Types.Header as I

