{-# LANGUAGE NoMonomorphismRestriction #-}
module Data.ByteString.Char8.AsBs where
-- generated by rvion/jetpack-gen 

import Data.ByteString.Char8 as I

-- ($wa) doesn't seem to be exported
-- ($wa1) doesn't seem to be exported
-- ($wa2) doesn't seem to be exported
-- ($wfindIndices) doesn't seem to be exported
-- ($wfirst) doesn't seem to be exported
-- ($wgroupBy) doesn't seem to be exported
-- ($wlines) doesn't seem to be exported
-- ($wloop) doesn't seem to be exported
-- ($wmapAccumL) doesn't seem to be exported
-- ($wmapAccumR) doesn't seem to be exported
-- ($wreadInt) doesn't seem to be exported
-- ($wreadInteger) doesn't seem to be exported
-- ($wscanl) doesn't seem to be exported
-- ($wscanl1) doesn't seem to be exported
-- ($wscanr) doesn't seem to be exported
-- ($wscanr1) doesn't seem to be exported
-- ($wzip) doesn't seem to be exported
-- ($wzipWith) doesn't seem to be exported

bs_all =  I.all

bs_any =  I.any

bs_appendFile =  I.appendFile
-- (appendFile1) doesn't seem to be exported

bs_break =  I.break
-- (break1) doesn't seem to be exported
-- (breakChar) doesn't seem to be exported

bs_breakEnd =  I.breakEnd
-- (breakSpace) doesn't seem to be exported

bs_concatMap =  I.concatMap

bs_cons =  I.cons

bs_count =  I.count
-- (dropSpace) doesn't seem to be exported

bs_dropWhile =  I.dropWhile
-- (dropWhile1) doesn't seem to be exported

bs_elem =  I.elem

bs_elemIndex =  I.elemIndex

bs_elemIndexEnd =  I.elemIndexEnd

bs_elemIndices =  I.elemIndices

bs_filter =  I.filter

bs_find =  I.find

bs_findIndex =  I.findIndex

bs_findIndices =  I.findIndices
-- (firstnonspace) doesn't seem to be exported
-- (firstspace) doesn't seem to be exported

bs_foldl =  I.foldl

bs_foldl' =  I.foldl'

bs_foldl1 =  I.foldl1

bs_foldl1' =  I.foldl1'

bs_foldr =  I.foldr

bs_foldr' =  I.foldr'

bs_foldr1 =  I.foldr1

bs_foldr1' =  I.foldr1'

bs_groupBy =  I.groupBy

bs_hPutStrLn =  I.hPutStrLn
-- (hPutStrLn1) doesn't seem to be exported
-- (hPutStrLn2) doesn't seem to be exported
-- (hPutStrLn3) doesn't seem to be exported

bs_head =  I.head

bs_index =  I.index

bs_intersperse =  I.intersperse

bs_last =  I.last

bs_lines =  I.lines

bs_map =  I.map

bs_mapAccumL =  I.mapAccumL

bs_mapAccumR =  I.mapAccumR

bs_maximum =  I.maximum

bs_minimum =  I.minimum

bs_notElem =  I.notElem

bs_pack =  I.pack

bs_putStrLn =  I.putStrLn
-- (putStrLn1) doesn't seem to be exported

bs_readFile =  I.readFile
-- (readFile1) doesn't seem to be exported
-- (readFile2) doesn't seem to be exported

bs_readInt =  I.readInt
-- (readInt_$s$wloop) doesn't seem to be exported
-- (readInt_$s$wloop1) doesn't seem to be exported

bs_readInteger =  I.readInteger

bs_replicate =  I.replicate

bs_scanl =  I.scanl

bs_scanl1 =  I.scanl1

bs_scanr =  I.scanr

bs_scanr1 =  I.scanr1

bs_singleton =  I.singleton

bs_snoc =  I.snoc

bs_span =  I.span

bs_spanEnd =  I.spanEnd

bs_split =  I.split

bs_splitWith =  I.splitWith

bs_takeWhile =  I.takeWhile

bs_uncons =  I.uncons

bs_unfoldr =  I.unfoldr
-- (unfoldr1) doesn't seem to be exported

bs_unfoldrN =  I.unfoldrN

bs_unlines =  I.unlines
-- (unlines1) doesn't seem to be exported
-- (unlines_nl) doesn't seem to be exported

bs_unpack =  I.unpack

bs_unsnoc =  I.unsnoc

bs_unwords =  I.unwords

bs_unzip =  I.unzip

bs_words =  I.words

bs_writeFile =  I.writeFile
-- (writeFile1) doesn't seem to be exported

bs_zip =  I.zip

bs_zipWith =  I.zipWith
-- (zip_$s$wzip) doesn't seem to be exported
