module Data.Map.AsMap_lazy where
-- generated by rvion/jetpack-gen 

import Data.Map as I

map_lazy_fold = I.fold
map_lazy_foldWithKey = I.foldWithKey
map_lazy_insertLookupWithKey' = I.insertLookupWithKey'
map_lazy_insertWith' = I.insertWith'
map_lazy_insertWithKey' = I.insertWithKey'
