 -- generated by rvion/jetpack-gen 
module Data.Text.Encoding.AsT where
import Data.Text.Encoding

-- ($fEqCodePoint) doesn't seem to be exported
-- ($fEqCodePoint_$c/=) doesn't seem to be exported
-- ($fEqCodePoint_$c==) doesn't seem to be exported
-- ($fEqDecoderState) doesn't seem to be exported
-- ($fEqDecoderState_$c/=) doesn't seem to be exported
-- ($fEqDecoderState_$c==) doesn't seem to be exported
-- ($fNumCodePoint) doesn't seem to be exported
-- ($fNumCodePoint_$c*) doesn't seem to be exported
-- ($fNumCodePoint_$c+) doesn't seem to be exported
-- ($fNumCodePoint_$c-) doesn't seem to be exported
-- ($fNumCodePoint_$cabs) doesn't seem to be exported
-- ($fNumCodePoint_$cfromInteger) doesn't seem to be exported
-- ($fNumCodePoint_$cnegate) doesn't seem to be exported
-- ($fNumCodePoint_$csignum) doesn't seem to be exported
-- ($fNumDecoderState) doesn't seem to be exported
-- ($fNumDecoderState_$c*) doesn't seem to be exported
-- ($fNumDecoderState_$c+) doesn't seem to be exported
-- ($fNumDecoderState_$c-) doesn't seem to be exported
-- ($fNumDecoderState_$cabs) doesn't seem to be exported
-- ($fNumDecoderState_$cfromInteger) doesn't seem to be exported
-- ($fNumDecoderState_$cnegate) doesn't seem to be exported
-- ($fNumDecoderState_$csignum) doesn't seem to be exported
-- ($fShowCodePoint) doesn't seem to be exported
-- ($fShowCodePoint1) doesn't seem to be exported
-- ($fShowCodePoint2) doesn't seem to be exported
-- ($fShowCodePoint_$cshow) doesn't seem to be exported
-- ($fShowCodePoint_$cshowList) doesn't seem to be exported
-- ($fShowCodePoint_$cshowsPrec) doesn't seem to be exported
-- ($fShowDecoderState) doesn't seem to be exported
-- ($fShowDecoderState1) doesn't seem to be exported
-- ($fShowDecoderState2) doesn't seem to be exported
-- ($fShowDecoderState_$cshow) doesn't seem to be exported
-- ($fShowDecoderState_$cshowList) doesn't seem to be exported
-- ($fShowDecoderState_$cshowsPrec) doesn't seem to be exported
-- ($fShowDecoding) doesn't seem to be exported
-- ($fShowDecoding1) doesn't seem to be exported
-- ($fShowDecoding2) doesn't seem to be exported
-- ($fShowDecoding3) doesn't seem to be exported
-- ($fShowDecoding_$cshow) doesn't seem to be exported
-- ($fShowDecoding_$cshowList) doesn't seem to be exported
-- ($fShowDecoding_$cshowsPrec) doesn't seem to be exported
-- ($fStorableCodePoint) doesn't seem to be exported
-- ($fStorableCodePoint_$calignment) doesn't seem to be exported
-- ($fStorableCodePoint_$cpeek) doesn't seem to be exported
-- ($fStorableCodePoint_$cpeekByteOff) doesn't seem to be exported
-- ($fStorableCodePoint_$cpeekElemOff) doesn't seem to be exported
-- ($fStorableCodePoint_$cpoke) doesn't seem to be exported
-- ($fStorableCodePoint_$cpokeByteOff) doesn't seem to be exported
-- ($fStorableCodePoint_$cpokeElemOff) doesn't seem to be exported
-- ($fStorableDecoderState) doesn't seem to be exported
-- ($fStorableDecoderState_$calignment) doesn't seem to be exported
-- ($fStorableDecoderState_$cpeek) doesn't seem to be exported
-- ($fStorableDecoderState_$cpeekByteOff) doesn't seem to be exported
-- ($fStorableDecoderState_$cpeekElemOff) doesn't seem to be exported
-- ($fStorableDecoderState_$cpoke) doesn't seem to be exported
-- ($fStorableDecoderState_$cpokeByteOff) doesn't seem to be exported
-- ($fStorableDecoderState_$cpokeElemOff) doesn't seem to be exported
-- ($s$dmshow1) doesn't seem to be exported
-- ($w$cshowsPrec) doesn't seem to be exported
-- ($w$cshowsPrec1) doesn't seem to be exported
-- ($w$cshowsPrec2) doesn't seem to be exported
-- ($wa) doesn't seem to be exported
-- ($wdecodeLatin1) doesn't seem to be exported
-- ($wdecodeUtf8With) doesn't seem to be exported
-- ($wencodeUtf8) doesn't seem to be exported
-- ($wstreamDecodeUtf8With) doesn't seem to be exported
-- (CodePoint) doesn't seem to be exported
-- (DecoderState) doesn't seem to be exported

type T_Decoding = T.Decoding

t_decodeASCII :: ByteString -> Text
t_decodeASCII =  T.decodeASCII

t_decodeLatin1 :: ByteString -> Text
t_decodeLatin1 =  T.decodeLatin1

t_decodeUtf16BE :: ByteString -> Text
t_decodeUtf16BE =  T.decodeUtf16BE

t_decodeUtf16BEWith :: OnDecodeError -> ByteString -> Text
t_decodeUtf16BEWith =  T.decodeUtf16BEWith

t_decodeUtf16LE :: ByteString -> Text
t_decodeUtf16LE =  T.decodeUtf16LE

t_decodeUtf16LEWith :: OnDecodeError -> ByteString -> Text
t_decodeUtf16LEWith =  T.decodeUtf16LEWith

t_decodeUtf32BE :: ByteString -> Text
t_decodeUtf32BE =  T.decodeUtf32BE

t_decodeUtf32BEWith :: OnDecodeError -> ByteString -> Text
t_decodeUtf32BEWith =  T.decodeUtf32BEWith

t_decodeUtf32LE :: ByteString -> Text
t_decodeUtf32LE =  T.decodeUtf32LE

t_decodeUtf32LEWith :: OnDecodeError -> ByteString -> Text
t_decodeUtf32LEWith =  T.decodeUtf32LEWith

t_decodeUtf8 :: ByteString -> Text
t_decodeUtf8 =  T.decodeUtf8

t_decodeUtf8' :: ByteString -> Either UnicodeException Text
t_decodeUtf8' =  T.decodeUtf8'

t_decodeUtf8With :: OnDecodeError -> ByteString -> Text
t_decodeUtf8With =  T.decodeUtf8With
-- (decodeUtf8_desc) doesn't seem to be exported

t_encodeUtf16BE :: Text -> ByteString
t_encodeUtf16BE =  T.encodeUtf16BE

t_encodeUtf16LE :: Text -> ByteString
t_encodeUtf16LE =  T.encodeUtf16LE

t_encodeUtf32BE :: Text -> ByteString
t_encodeUtf32BE =  T.encodeUtf32BE

t_encodeUtf32LE :: Text -> ByteString
t_encodeUtf32LE =  T.encodeUtf32LE

t_encodeUtf8 :: Text -> ByteString
t_encodeUtf8 =  T.encodeUtf8

t_encodeUtf8Builder :: Text -> Builder
t_encodeUtf8Builder =  T.encodeUtf8Builder
-- (encodeUtf8Builder1) doesn't seem to be exported

t_encodeUtf8BuilderEscaped :: BoundedPrim Word8 -> Text -> Builder
t_encodeUtf8BuilderEscaped =  T.encodeUtf8BuilderEscaped

t_streamDecodeUtf8 :: ByteString -> Decoding
t_streamDecodeUtf8 =  T.streamDecodeUtf8

t_streamDecodeUtf8With :: OnDecodeError -> ByteString -> Decoding
t_streamDecodeUtf8With =  T.streamDecodeUtf8With
