 -- generated by rvion/jetpack-gen 
module Data.Text.IO.AsT where
import Data.Text.IO


t_appendFile :: FilePath -> Text -> IO ()
t_appendFile =  T.appendFile
-- (appendFile1) doesn't seem to be exported
-- (appendFile2) doesn't seem to be exported

t_getContents :: IO Text
t_getContents =  T.getContents
-- (getContents1) doesn't seem to be exported
-- (getContents2) doesn't seem to be exported

t_getLine :: IO Text
t_getLine =  T.getLine
-- (getLine1) doesn't seem to be exported

t_hGetChunk :: Handle -> IO Text
t_hGetChunk =  T.hGetChunk
-- (hGetChunk1) doesn't seem to be exported
-- (hGetChunk2) doesn't seem to be exported
-- (hGetChunk3) doesn't seem to be exported
-- (hGetChunk4) doesn't seem to be exported

t_hGetContents :: Handle -> IO Text
t_hGetContents =  T.hGetContents

t_hGetLine :: Handle -> IO Text
t_hGetLine =  T.hGetLine
-- (hGetLine1) doesn't seem to be exported

t_hPutStr :: Handle -> Text -> IO ()
t_hPutStr =  T.hPutStr

t_hPutStrLn :: Handle -> Text -> IO ()
t_hPutStrLn =  T.hPutStrLn
-- (hPutStrLn1) doesn't seem to be exported

t_interact :: (Text -> Text) -> IO ()
t_interact =  T.interact
-- (interact1) doesn't seem to be exported

t_putStr :: Text -> IO ()
t_putStr =  T.putStr
-- (putStr1) doesn't seem to be exported

t_putStrLn :: Text -> IO ()
t_putStrLn =  T.putStrLn
-- (putStrLn1) doesn't seem to be exported

t_readFile :: FilePath -> IO Text
t_readFile =  T.readFile
-- (readFile1) doesn't seem to be exported

t_writeFile :: FilePath -> Text -> IO ()
t_writeFile =  T.writeFile
-- (writeFile1) doesn't seem to be exported
