module System.IO.Strict.AsSio
  ( module System.IO.Strict.AsSio
  ) where
-- generated by https://github.com/rvion/ride/tree/master/jetpack-gen

import qualified System.IO.Strict as I


-- sio_getContents :: IO String
sio_getContents = I.getContents

-- sio_hGetContents :: Handle -> IO String
sio_hGetContents = I.hGetContents

-- sio_interact :: (String -> String) -> IO ()
sio_interact = I.interact

-- sio_readFile :: FilePath -> IO String
sio_readFile = I.readFile
