module Control.Monad.IO.Class.AsTrans where
-- generated by https://github.com/rvion/ride/tree/master/jetpack-gen

import qualified Control.Monad.IO.Class as I


-- trans_liftIO :: forall a. IO a -> m a
trans_liftIO = I.liftIO
