module Data.Aeson.Lens.AsJs where
-- generated by https://github.com/rvion/ride/tree/master/jetpack-gen

import Data.Aeson.Lens as I

-- js__Integral :: forall t a. (AsNumber t, Integral a) => Prism' t a
js__Integral = I._Integral

-- js_key :: forall t. AsValue t => Text -> Traversal' t Value
js_key = I.key

-- js_members :: forall t. AsValue t => IndexedTraversal' Text t Value
js_members = I.members

-- js_nonNull :: Prism' Value Value
js_nonNull = I.nonNull

-- js_nth :: forall t. AsValue t => Int -> Traversal' t Value
js_nth = I.nth

-- js_values :: forall t. AsValue t => IndexedTraversal' Int t Value
js_values = I.values

type JsPrimitive  = I.Primitive
