module Data.Aeson.Lens.AsJson where
-- generated by https://github.com/rvion/ride/tree/master/jetpack-gen

import Data.Aeson.Lens as I

-- json__Integral :: forall t a. (AsNumber t, Integral a) => Prism' t a
json__Integral = I._Integral

-- json_key :: forall t. AsValue t => Text -> Traversal' t Value
json_key = I.key

-- json_members :: forall t. AsValue t => IndexedTraversal' Text t Value
json_members = I.members

-- json_nonNull :: Prism' Value Value
json_nonNull = I.nonNull

-- json_nth :: forall t. AsValue t => Int -> Traversal' t Value
json_nth = I.nth

-- json_values :: forall t. AsValue t => IndexedTraversal' Int t Value
json_values = I.values

type JsonPrimitive  = I.Primitive
