-- generated by rvion/jetpack-gen 
module AsNe where
import Data.List.NonEmpty


ne_!! :: forall a. NonEmpty a -> Int -> a
ne_!! =  T.!!
-- ($c>>=) doesn't seem to be exported
-- ($cfoldr) doesn't seem to be exported
-- ($cr2x4) doesn't seem to be exported
-- ($fApplicativeNonEmpty) doesn't seem to be exported
-- ($fApplicativeNonEmpty1) doesn't seem to be exported
-- ($fApplicativeNonEmpty_$c*>) doesn't seem to be exported
-- ($fApplicativeNonEmpty_$c<*) doesn't seem to be exported
-- ($fApplicativeNonEmpty_$c<*>) doesn't seem to be exported
-- ($fApplicativeNonEmpty_$cpure) doesn't seem to be exported
-- ($fConstructorNonEmpty) doesn't seem to be exported
-- ($fConstructorNonEmpty1) doesn't seem to be exported
-- ($fConstructorNonEmpty2) doesn't seem to be exported
-- ($fConstructorNonEmpty3) doesn't seem to be exported
-- ($fConstructorNonEmpty_$cconFixity) doesn't seem to be exported
-- ($fConstructorNonEmpty_$cconName) doesn't seem to be exported
-- ($fConstructorNonEmpty_$s$dmconIsRecord) doesn't seem to be exported
-- ($fDataNonEmpty) doesn't seem to be exported
-- ($fDataNonEmpty1) doesn't seem to be exported
-- ($fDataNonEmpty10) doesn't seem to be exported
-- ($fDataNonEmpty11) doesn't seem to be exported
-- ($fDataNonEmpty12) doesn't seem to be exported
-- ($fDataNonEmpty13) doesn't seem to be exported
-- ($fDataNonEmpty2) doesn't seem to be exported
-- ($fDataNonEmpty3) doesn't seem to be exported
-- ($fDataNonEmpty4) doesn't seem to be exported
-- ($fDataNonEmpty5) doesn't seem to be exported
-- ($fDataNonEmpty6) doesn't seem to be exported
-- ($fDataNonEmpty7) doesn't seem to be exported
-- ($fDataNonEmpty8) doesn't seem to be exported
-- ($fDataNonEmpty9) doesn't seem to be exported
-- ($fDataNonEmpty_$cdataCast1) doesn't seem to be exported
-- ($fDataNonEmpty_$cdataCast2) doesn't seem to be exported
-- ($fDataNonEmpty_$cdataTypeOf) doesn't seem to be exported
-- ($fDataNonEmpty_$cgfoldl) doesn't seem to be exported
-- ($fDataNonEmpty_$cgmapM) doesn't seem to be exported
-- ($fDataNonEmpty_$cgmapMo) doesn't seem to be exported
-- ($fDataNonEmpty_$cgmapMp) doesn't seem to be exported
-- ($fDataNonEmpty_$cgmapQ) doesn't seem to be exported
-- ($fDataNonEmpty_$cgmapQi) doesn't seem to be exported
-- ($fDataNonEmpty_$cgmapQl) doesn't seem to be exported
-- ($fDataNonEmpty_$cgmapQr) doesn't seem to be exported
-- ($fDataNonEmpty_$cgmapT) doesn't seem to be exported
-- ($fDataNonEmpty_$cgunfold) doesn't seem to be exported
-- ($fDataNonEmpty_$ctoConstr) doesn't seem to be exported
-- ($fDataNonEmpty_ww2) doesn't seem to be exported
-- ($fDataNonEmpty_ww3) doesn't seem to be exported
-- ($fDataNonEmpty_ww4) doesn't seem to be exported
-- ($fDatatypeNonEmpty) doesn't seem to be exported
-- ($fDatatypeNonEmpty1) doesn't seem to be exported
-- ($fDatatypeNonEmpty_$cdatatypeName) doesn't seem to be exported
-- ($fDatatypeNonEmpty_$cmoduleName) doesn't seem to be exported
-- ($fDatatypeNonEmpty_$s$dmisNewtype) doesn't seem to be exported
-- ($fEqNonEmpty) doesn't seem to be exported
-- ($fEqNonEmpty_$c/=) doesn't seem to be exported
-- ($fEqNonEmpty_$c==) doesn't seem to be exported
-- ($fFoldableNonEmpty) doesn't seem to be exported
-- ($fFoldableNonEmpty1) doesn't seem to be exported
-- ($fFoldableNonEmpty2) doesn't seem to be exported
-- ($fFoldableNonEmpty3) doesn't seem to be exported
-- ($fFoldableNonEmpty4) doesn't seem to be exported
-- ($fFoldableNonEmpty_$celem) doesn't seem to be exported
-- ($fFoldableNonEmpty_$cfold) doesn't seem to be exported
-- ($fFoldableNonEmpty_$cfoldMap) doesn't seem to be exported
-- ($fFoldableNonEmpty_$cfoldl) doesn't seem to be exported
-- ($fFoldableNonEmpty_$cfoldl') doesn't seem to be exported
-- ($fFoldableNonEmpty_$cfoldl1) doesn't seem to be exported
-- ($fFoldableNonEmpty_$cfoldr') doesn't seem to be exported
-- ($fFoldableNonEmpty_$cfoldr1) doesn't seem to be exported
-- ($fFoldableNonEmpty_$clength) doesn't seem to be exported
-- ($fFoldableNonEmpty_$cmaximum) doesn't seem to be exported
-- ($fFoldableNonEmpty_$cminimum) doesn't seem to be exported
-- ($fFoldableNonEmpty_$cnull) doesn't seem to be exported
-- ($fFoldableNonEmpty_$cproduct) doesn't seem to be exported
-- ($fFoldableNonEmpty_$csum) doesn't seem to be exported
-- ($fFoldableNonEmpty_$ctoList) doesn't seem to be exported
-- ($fFunctorNonEmpty) doesn't seem to be exported
-- ($fFunctorNonEmpty_$c<$) doesn't seem to be exported
-- ($fGeneric1NonEmpty) doesn't seem to be exported
-- ($fGeneric1NonEmpty_$cfrom1) doesn't seem to be exported
-- ($fGeneric1NonEmpty_$cto1) doesn't seem to be exported
-- ($fGenericNonEmpty) doesn't seem to be exported
-- ($fGenericNonEmpty_$cfrom) doesn't seem to be exported
-- ($fGenericNonEmpty_$cto) doesn't seem to be exported
-- ($fHashableNonEmpty) doesn't seem to be exported
-- ($fHashableNonEmpty_$chash) doesn't seem to be exported
-- ($fHashableNonEmpty_$chashWithSalt) doesn't seem to be exported
-- ($fIsListNonEmpty) doesn't seem to be exported
-- ($fIsListNonEmpty1) doesn't seem to be exported
-- ($fIsListNonEmpty_$cfromListN) doesn't seem to be exported
-- ($fMonadFixNonEmpty) doesn't seem to be exported
-- ($fMonadFixNonEmpty_$cmfix) doesn't seem to be exported
-- ($fMonadNonEmpty) doesn't seem to be exported
-- ($fMonadNonEmpty_$c>>) doesn't seem to be exported
-- ($fMonadNonEmpty_$s$dmfail) doesn't seem to be exported
-- ($fMonadZipNonEmpty) doesn't seem to be exported
-- ($fMonadZipNonEmpty_$cmunzip) doesn't seem to be exported
-- ($fMonadZipNonEmpty_$s<$>) doesn't seem to be exported
-- ($fMonadZipNonEmpty_$sunzip) doesn't seem to be exported
-- ($fNFDataNonEmpty) doesn't seem to be exported
-- ($fNFDataNonEmpty_$crnf) doesn't seem to be exported
-- ($fOrdNonEmpty) doesn't seem to be exported
-- ($fOrdNonEmpty_$c<) doesn't seem to be exported
-- ($fOrdNonEmpty_$c<=) doesn't seem to be exported
-- ($fOrdNonEmpty_$c>) doesn't seem to be exported
-- ($fOrdNonEmpty_$c>=) doesn't seem to be exported
-- ($fOrdNonEmpty_$ccompare) doesn't seem to be exported
-- ($fOrdNonEmpty_$cmax) doesn't seem to be exported
-- ($fOrdNonEmpty_$cmin) doesn't seem to be exported
-- ($fReadNonEmpty) doesn't seem to be exported
-- ($fReadNonEmpty1) doesn't seem to be exported
-- ($fReadNonEmpty2) doesn't seem to be exported
-- ($fReadNonEmpty3) doesn't seem to be exported
-- ($fReadNonEmpty_$creadList) doesn't seem to be exported
-- ($fReadNonEmpty_$creadListPrec) doesn't seem to be exported
-- ($fReadNonEmpty_$creadPrec) doesn't seem to be exported
-- ($fReadNonEmpty_$creadsPrec) doesn't seem to be exported
-- ($fShowNonEmpty) doesn't seem to be exported
-- ($fShowNonEmpty1) doesn't seem to be exported
-- ($fShowNonEmpty_$cshow) doesn't seem to be exported
-- ($fShowNonEmpty_$cshowList) doesn't seem to be exported
-- ($fShowNonEmpty_$cshowsPrec) doesn't seem to be exported
-- ($fTraversableNonEmpty) doesn't seem to be exported
-- ($fTraversableNonEmpty_$cmapM) doesn't seem to be exported
-- ($fTraversableNonEmpty_$csequence) doesn't seem to be exported
-- ($fTraversableNonEmpty_$csequenceA) doesn't seem to be exported
-- ($fTraversableNonEmpty_$ctraverse) doesn't seem to be exported
-- ($tr2ux) doesn't seem to be exported
-- ($w$c<) doesn't seem to be exported
-- ($w$c<*) doesn't seem to be exported
-- ($w$c<*>) doesn't seem to be exported
-- ($w$c<=) doesn't seem to be exported
-- ($w$c==) doesn't seem to be exported
-- ($w$c>) doesn't seem to be exported
-- ($w$c>=) doesn't seem to be exported
-- ($w$c>>=) doesn't seem to be exported
-- ($w$ccompare) doesn't seem to be exported
-- ($w$cfoldl) doesn't seem to be exported
-- ($w$cfoldl') doesn't seem to be exported
-- ($w$cfoldl1) doesn't seem to be exported
-- ($w$cfoldr') doesn't seem to be exported
-- ($w$cfoldr1) doesn't seem to be exported
-- ($w$cgfoldl) doesn't seem to be exported
-- ($w$cgmapM) doesn't seem to be exported
-- ($w$cgmapMo) doesn't seem to be exported
-- ($w$cgmapMp) doesn't seem to be exported
-- ($w$cgmapQ) doesn't seem to be exported
-- ($w$cgmapQi) doesn't seem to be exported
-- ($w$cgmapQl) doesn't seem to be exported
-- ($w$cgmapQr) doesn't seem to be exported
-- ($w$cgunfold) doesn't seem to be exported
-- ($w$cmaximum) doesn't seem to be exported
-- ($w$cminimum) doesn't seem to be exported
-- ($w$cshow) doesn't seem to be exported
-- ($w$cshowsPrec) doesn't seem to be exported
-- ($wa) doesn't seem to be exported
-- ($wtranspose) doesn't seem to be exported
-- ($wunfold) doesn't seem to be exported
-- ($wunfoldr) doesn't seem to be exported
-- ($wxor) doesn't seem to be exported

ne_<| :: forall a. a -> NonEmpty a -> NonEmpty a
ne_<| =  T.<|
-- (C1_0NonEmpty) doesn't seem to be exported
-- (D1NonEmpty) doesn't seem to be exported

type Ne_NonEmpty = T.NonEmpty
-- (Rep1_NonEmpty) doesn't seem to be exported
-- (Rep_NonEmpty) doesn't seem to be exported
-- (S1_0_0NonEmpty) doesn't seem to be exported
-- (S1_0_1NonEmpty) doesn't seem to be exported
-- (TFCo:R:ItemNonEmpty) doesn't seem to be exported

ne_break :: forall a. (a -> Bool) -> NonEmpty a -> ([a], [a])
ne_break =  T.break

ne_cons :: forall a. a -> NonEmpty a -> NonEmpty a
ne_cons =  T.cons

ne_cycle :: forall a. NonEmpty a -> NonEmpty a
ne_cycle =  T.cycle

ne_drop :: forall a. Int -> NonEmpty a -> [a]
ne_drop =  T.drop

ne_dropWhile :: forall a. (a -> Bool) -> NonEmpty a -> [a]
ne_dropWhile =  T.dropWhile

ne_filter :: forall a. (a -> Bool) -> NonEmpty a -> [a]
ne_filter =  T.filter

ne_fromList :: forall a. [a] -> NonEmpty a
ne_fromList =  T.fromList

ne_group :: forall (f :: * -> *) a. (Foldable f, Eq a) => f a -> [NonEmpty a]
ne_group =  T.group

ne_group1 :: forall a. Eq a => NonEmpty a -> NonEmpty (NonEmpty a)
ne_group1 =  T.group1

ne_groupAllWith :: forall a b. Ord b => (a -> b) -> [a] -> [NonEmpty a]
ne_groupAllWith =  T.groupAllWith

ne_groupAllWith1 :: forall a b.
  Ord b =>
  (a -> b) -> NonEmpty a -> NonEmpty (NonEmpty a)
ne_groupAllWith1 =  T.groupAllWith1

ne_groupBy :: forall a (f :: * -> *).
  Foldable f =>
  (a -> a -> Bool) -> f a -> [NonEmpty a]
ne_groupBy =  T.groupBy

ne_groupBy1 :: forall a. (a -> a -> Bool) -> NonEmpty a -> NonEmpty (NonEmpty a)
ne_groupBy1 =  T.groupBy1
-- (groupBy_$sgroupBy) doesn't seem to be exported

ne_groupWith :: forall a b (f :: * -> *).
  (Foldable f, Eq b) =>
  (a -> b) -> f a -> [NonEmpty a]
ne_groupWith =  T.groupWith

ne_groupWith1 :: forall a b. Eq b => (a -> b) -> NonEmpty a -> NonEmpty (NonEmpty a)
ne_groupWith1 =  T.groupWith1

ne_head :: forall a. NonEmpty a -> a
ne_head =  T.head

ne_init :: forall a. NonEmpty a -> [a]
ne_init =  T.init

ne_inits :: forall (f :: * -> *) a. Foldable f => f a -> NonEmpty [a]
ne_inits =  T.inits

ne_insert :: forall a (f :: * -> *).
  (Foldable f, Ord a) =>
  a -> f a -> NonEmpty a
ne_insert =  T.insert

ne_intersperse :: forall a. a -> NonEmpty a -> NonEmpty a
ne_intersperse =  T.intersperse

ne_isPrefixOf :: forall a. Eq a => [a] -> NonEmpty a -> Bool
ne_isPrefixOf =  T.isPrefixOf

ne_iterate :: forall a. (a -> a) -> a -> NonEmpty a
ne_iterate =  T.iterate

ne_last :: forall a. NonEmpty a -> a
ne_last =  T.last

ne_length :: forall a. NonEmpty a -> Int
ne_length =  T.length

ne_lines :: NonEmpty Char -> NonEmpty String
ne_lines =  T.lines

ne_map :: forall a b. (a -> b) -> NonEmpty a -> NonEmpty b
ne_map =  T.map

ne_nonEmpty :: forall a. [a] -> Maybe (NonEmpty a)
ne_nonEmpty =  T.nonEmpty

ne_nub :: forall a. Eq a => NonEmpty a -> NonEmpty a
ne_nub =  T.nub

ne_nubBy :: forall a. (a -> a -> Bool) -> NonEmpty a -> NonEmpty a
ne_nubBy =  T.nubBy

ne_partition :: forall a. (a -> Bool) -> NonEmpty a -> ([a], [a])
ne_partition =  T.partition

ne_repeat :: forall a. a -> NonEmpty a
ne_repeat =  T.repeat

ne_reverse :: forall a. NonEmpty a -> NonEmpty a
ne_reverse =  T.reverse

ne_scanl :: forall b a (f :: * -> *).
  Foldable f =>
  (b -> a -> b) -> b -> f a -> NonEmpty b
ne_scanl =  T.scanl

ne_scanl1 :: forall a. (a -> a -> a) -> NonEmpty a -> NonEmpty a
ne_scanl1 =  T.scanl1

ne_scanr :: forall a b (f :: * -> *).
  Foldable f =>
  (a -> b -> b) -> b -> f a -> NonEmpty b
ne_scanr =  T.scanr

ne_scanr1 :: forall a. (a -> a -> a) -> NonEmpty a -> NonEmpty a
ne_scanr1 =  T.scanr1

ne_some1 :: forall (f :: * -> *) a. Alternative f => f a -> f (NonEmpty a)
ne_some1 =  T.some1

ne_sort :: forall a. Ord a => NonEmpty a -> NonEmpty a
ne_sort =  T.sort

ne_sortBy :: forall a. (a -> a -> Ordering) -> NonEmpty a -> NonEmpty a
ne_sortBy =  T.sortBy
-- (sortBy1) doesn't seem to be exported

ne_sortWith :: forall a o. Ord o => (a -> o) -> NonEmpty a -> NonEmpty a
ne_sortWith =  T.sortWith

ne_span :: forall a. (a -> Bool) -> NonEmpty a -> ([a], [a])
ne_span =  T.span

ne_splitAt :: forall a. Int -> NonEmpty a -> ([a], [a])
ne_splitAt =  T.splitAt

ne_tail :: forall a. NonEmpty a -> [a]
ne_tail =  T.tail

ne_tails :: forall (f :: * -> *) a. Foldable f => f a -> NonEmpty [a]
ne_tails =  T.tails

ne_take :: forall a. Int -> NonEmpty a -> [a]
ne_take =  T.take

ne_takeWhile :: forall a. (a -> Bool) -> NonEmpty a -> [a]
ne_takeWhile =  T.takeWhile

ne_toList :: forall a. NonEmpty a -> [a]
ne_toList =  T.toList

ne_transpose :: forall a. NonEmpty (NonEmpty a) -> NonEmpty (NonEmpty a)
ne_transpose =  T.transpose
-- (transpose1) doesn't seem to be exported

ne_uncons :: forall a. NonEmpty a -> (a, Maybe (NonEmpty a))
ne_uncons =  T.uncons

ne_unfold :: forall a b. (a -> (b, Maybe a)) -> a -> NonEmpty b
ne_unfold =  T.unfold

ne_unfoldr :: forall a b. (a -> (b, Maybe a)) -> a -> NonEmpty b
ne_unfoldr =  T.unfoldr

ne_unlines :: NonEmpty String -> NonEmpty Char
ne_unlines =  T.unlines

ne_unwords :: NonEmpty String -> NonEmpty Char
ne_unwords =  T.unwords

ne_unzip :: forall (f :: * -> *) a b. Functor f => f (a, b) -> (f a, f b)
ne_unzip =  T.unzip

ne_words :: NonEmpty Char -> NonEmpty String
ne_words =  T.words

ne_xor :: NonEmpty Bool -> Bool
ne_xor =  T.xor

ne_zip :: forall a b. NonEmpty a -> NonEmpty b -> NonEmpty (a, b)
ne_zip =  T.zip

ne_zipWith :: forall a b c.
  (a -> b -> c) -> NonEmpty a -> NonEmpty b -> NonEmpty c
ne_zipWith =  T.zipWith
