{-# LANGUAGE NoMonomorphismRestriction #-}
module Data.ByteString.AsBs where
-- generated by rvion/jetpack-gen 

import Data.ByteString as I

-- ($wa) doesn't seem to be exported
-- ($wa1) doesn't seem to be exported
-- ($wa10) doesn't seem to be exported
-- ($wa2) doesn't seem to be exported
-- ($wa3) doesn't seem to be exported
-- ($wa4) doesn't seem to be exported
-- ($wa5) doesn't seem to be exported
-- ($wa6) doesn't seem to be exported
-- ($wa7) doesn't seem to be exported
-- ($wa8) doesn't seem to be exported
-- ($wa9) doesn't seem to be exported
-- ($wbreakSubstring) doesn't seem to be exported
-- ($wconcatMap) doesn't seem to be exported
-- ($wcopy) doesn't seem to be exported
-- ($wfindFromEndUntil) doesn't seem to be exported
-- ($wfindIndices) doesn't seem to be exported
-- ($wfindSubstrings) doesn't seem to be exported
-- ($wgroup) doesn't seem to be exported
-- ($wgroupBy) doesn't seem to be exported
-- ($winits) doesn't seem to be exported
-- ($wintersperse) doesn't seem to be exported
-- ($wisPrefixOf) doesn't seem to be exported
-- ($wisSuffixOf) doesn't seem to be exported
-- ($wpartition) doesn't seem to be exported
-- ($wreplicate) doesn't seem to be exported
-- ($wreverse) doesn't seem to be exported
-- ($wsort) doesn't seem to be exported
-- ($wtails) doesn't seem to be exported
-- ($wzip) doesn't seem to be exported
-- ($wzipWith) doesn't seem to be exported

bs_all =  I.all

bs_any =  I.any

bs_append =  I.append

bs_appendFile =  I.appendFile
-- (appendFile1) doesn't seem to be exported
-- (appendFile2) doesn't seem to be exported

bs_break =  I.break

bs_breakByte =  I.breakByte

bs_breakEnd =  I.breakEnd

bs_breakSubstring =  I.breakSubstring

bs_concat =  I.concat

bs_concatMap =  I.concatMap

bs_cons =  I.cons

bs_copy =  I.copy

bs_count =  I.count

bs_drop =  I.drop

bs_dropWhile =  I.dropWhile

bs_elem =  I.elem

bs_elemIndex =  I.elemIndex

bs_elemIndexEnd =  I.elemIndexEnd

bs_elemIndices =  I.elemIndices

bs_empty =  I.empty
-- (errorEmptyList) doesn't seem to be exported

bs_filter =  I.filter

bs_find =  I.find

bs_findIndex =  I.findIndex

bs_findIndices =  I.findIndices

bs_findSubstring =  I.findSubstring

bs_findSubstrings =  I.findSubstrings

bs_foldl =  I.foldl

bs_foldl' =  I.foldl'

bs_foldl1 =  I.foldl1

bs_foldl1' =  I.foldl1'

bs_foldr =  I.foldr

bs_foldr' =  I.foldr'

bs_foldr1 =  I.foldr1

bs_foldr1' =  I.foldr1'

bs_getContents =  I.getContents
-- (getContents1) doesn't seem to be exported
-- (getContents2) doesn't seem to be exported
-- (getContents3) doesn't seem to be exported
-- (getContents4) doesn't seem to be exported
-- (getContents5) doesn't seem to be exported

bs_getLine =  I.getLine
-- (getLine1) doesn't seem to be exported
-- (getLine2) doesn't seem to be exported
-- (getLine3) doesn't seem to be exported

bs_group =  I.group

bs_groupBy =  I.groupBy

bs_hGet =  I.hGet
-- (hGet1) doesn't seem to be exported
-- (hGet2) doesn't seem to be exported

bs_hGetContents =  I.hGetContents

bs_hGetLine =  I.hGetLine
-- (hGetLine1) doesn't seem to be exported

bs_hGetNonBlocking =  I.hGetNonBlocking
-- (hGetNonBlocking1) doesn't seem to be exported
-- (hGetNonBlocking2) doesn't seem to be exported

bs_hGetSome =  I.hGetSome
-- (hGetSome1) doesn't seem to be exported
-- (hGetSome2) doesn't seem to be exported

bs_hPut =  I.hPut

bs_hPutNonBlocking =  I.hPutNonBlocking
-- (hPutNonBlocking1) doesn't seem to be exported

bs_hPutStr =  I.hPutStr

bs_hPutStrLn =  I.hPutStrLn
-- (hPutStrLn1) doesn't seem to be exported
-- (hPutStrLn2) doesn't seem to be exported
-- (hPutStrLn3) doesn't seem to be exported

bs_head =  I.head

bs_index =  I.index

bs_init =  I.init

bs_inits =  I.inits

bs_interact =  I.interact
-- (interact1) doesn't seem to be exported

bs_intercalate =  I.intercalate
-- (intercalateWithByte) doesn't seem to be exported

bs_intersperse =  I.intersperse

bs_isInfixOf =  I.isInfixOf

bs_isPrefixOf =  I.isPrefixOf

bs_isSuffixOf =  I.isSuffixOf

bs_last =  I.last

bs_length =  I.length

bs_map =  I.map

bs_mapAccumL =  I.mapAccumL

bs_mapAccumR =  I.mapAccumR

bs_maximum =  I.maximum

bs_minimum =  I.minimum
-- (moduleError) doesn't seem to be exported
-- (moduleErrorIO) doesn't seem to be exported

bs_notElem =  I.notElem

bs_null =  I.null

bs_pack =  I.pack

bs_packCString =  I.packCString
-- (packCString1) doesn't seem to be exported
-- (packCString2) doesn't seem to be exported
-- (packCString3) doesn't seem to be exported

bs_packCStringLen =  I.packCStringLen

bs_partition =  I.partition

bs_putStr =  I.putStr
-- (putStr1) doesn't seem to be exported

bs_putStrLn =  I.putStrLn
-- (putStrLn1) doesn't seem to be exported

bs_readFile =  I.readFile
-- (readFile1) doesn't seem to be exported
-- (readFile2) doesn't seem to be exported
-- (readFile3) doesn't seem to be exported

bs_replicate =  I.replicate

bs_reverse =  I.reverse

bs_scanl =  I.scanl

bs_scanl1 =  I.scanl1

bs_scanr =  I.scanr

bs_scanr1 =  I.scanr1

bs_singleton =  I.singleton

bs_snoc =  I.snoc

bs_sort =  I.sort

bs_span =  I.span
-- (spanByte) doesn't seem to be exported

bs_spanEnd =  I.spanEnd

bs_split =  I.split

bs_splitAt =  I.splitAt

bs_splitWith =  I.splitWith

bs_tail =  I.tail

bs_tails =  I.tails

bs_take =  I.take

bs_takeWhile =  I.takeWhile

bs_transpose =  I.transpose

bs_uncons =  I.uncons

bs_unfoldr =  I.unfoldr

bs_unfoldrN =  I.unfoldrN

bs_unpack =  I.unpack
-- (unpackFoldr) doesn't seem to be exported

bs_unsnoc =  I.unsnoc

bs_unzip =  I.unzip

bs_useAsCString =  I.useAsCString
-- (useAsCString1) doesn't seem to be exported

bs_useAsCStringLen =  I.useAsCStringLen
-- (useAsCStringLen1) doesn't seem to be exported

bs_writeFile =  I.writeFile
-- (writeFile1) doesn't seem to be exported

bs_zip =  I.zip

bs_zipWith =  I.zipWith
-- (zipWith') doesn't seem to be exported
-- (zipWith_$s$wzipWith) doesn't seem to be exported
-- (zip_$s$wzip) doesn't seem to be exported
