module Network.Wai.Middleware.RequestLogger.AsWai where
-- generated by https://github.com/rvion/ride/tree/master/jetpack-gen

import qualified Network.Wai.Middleware.RequestLogger as I

-- wai_logStdout :: Middleware
wai_logStdout = I.logStdout

-- wai_logStdoutDev :: Middleware
wai_logStdoutDev = I.logStdoutDev

-- wai_mkRequestLogger :: RequestLoggerSettings -> IO Middleware
wai_mkRequestLogger = I.mkRequestLogger

type WaiCallback  = I.Callback
type WaiDestination  = I.Destination
type WaiOutputFormat  = I.OutputFormat
type WaiOutputFormatter  = I.OutputFormatter
type WaiOutputFormatterWithDetails  = I.OutputFormatterWithDetails
type WaiRequestLoggerSettings  = I.RequestLoggerSettings
type WaiIPAddrSource  = I.IPAddrSource
