{-# LANGUAGE NoMonomorphismRestriction #-}
module Data.Map.Strict.AsMap where
-- generated by rvion/jetpack-gen 

import Data.Map.Strict as I

-- ($winsertLookupWithKey) doesn't seem to be exported
-- ($wmapAccumL) doesn't seem to be exported
-- ($wmapAccumRWithKey) doesn't seem to be exported
-- ($wpoly_go) doesn't seem to be exported
-- ($wpoly_go1) doesn't seem to be exported
-- ($wupdateAt) doesn't seem to be exported
-- ($wupdateLookupWithKey) doesn't seem to be exported

map_adjust =  I.adjust

map_adjustWithKey =  I.adjustWithKey

map_alter =  I.alter

map_differenceWith =  I.differenceWith

map_differenceWithKey =  I.differenceWithKey

map_findWithDefault =  I.findWithDefault

map_fromAscList =  I.fromAscList

map_fromAscListWith =  I.fromAscListWith

map_fromAscListWithKey =  I.fromAscListWithKey

map_fromDistinctAscList =  I.fromDistinctAscList

map_fromList =  I.fromList

map_fromListWith =  I.fromListWith

map_fromListWithKey =  I.fromListWithKey

map_fromSet =  I.fromSet

map_insert =  I.insert

map_insertLookupWithKey =  I.insertLookupWithKey

map_insertWith =  I.insertWith

map_insertWithKey =  I.insertWithKey

map_intersectionWith =  I.intersectionWith

map_intersectionWithKey =  I.intersectionWithKey

map_map =  I.map

map_mapAccum =  I.mapAccum
-- (mapAccumL) doesn't seem to be exported

map_mapAccumRWithKey =  I.mapAccumRWithKey

map_mapAccumWithKey =  I.mapAccumWithKey

map_mapEither =  I.mapEither
-- (mapEither1) doesn't seem to be exported

map_mapEitherWithKey =  I.mapEitherWithKey

map_mapKeysWith =  I.mapKeysWith

map_mapMaybe =  I.mapMaybe

map_mapMaybeWithKey =  I.mapMaybeWithKey

map_mapWithKey =  I.mapWithKey

map_mergeWithKey =  I.mergeWithKey

map_singleton =  I.singleton

map_unionWith =  I.unionWith

map_unionWithKey =  I.unionWithKey

map_unionsWith =  I.unionsWith

map_update =  I.update

map_updateAt =  I.updateAt

map_updateLookupWithKey =  I.updateLookupWithKey

map_updateMax =  I.updateMax

map_updateMaxWithKey =  I.updateMaxWithKey
-- (updateMaxWithKey_$supdateMaxWithKey) doesn't seem to be exported

map_updateMin =  I.updateMin

map_updateMinWithKey =  I.updateMinWithKey
-- (updateMinWithKey_$supdateMinWithKey) doesn't seem to be exported

map_updateWithKey =  I.updateWithKey
