

module Data.Set.AsSet where
-- generated by rvion/jetpack-gen 

import Data.Set as I

set_delete = I.delete
set_deleteAt = I.deleteAt
set_deleteFindMax = I.deleteFindMax
set_deleteFindMin = I.deleteFindMin
set_deleteMax = I.deleteMax
set_deleteMin = I.deleteMin
set_difference = I.difference
set_elemAt = I.elemAt
set_elems = I.elems
set_empty = I.empty
set_filter = I.filter
set_findIndex = I.findIndex
set_findMax = I.findMax
set_findMin = I.findMin
set_fold = I.fold
set_foldl = I.foldl
set_foldl' = I.foldl'
set_foldr = I.foldr
set_foldr' = I.foldr'
set_fromAscList = I.fromAscList
set_fromDistinctAscList = I.fromDistinctAscList
set_fromList = I.fromList
set_insert = I.insert
set_intersection = I.intersection
set_isProperSubsetOf = I.isProperSubsetOf
set_isSubsetOf = I.isSubsetOf
set_lookupGE = I.lookupGE
set_lookupGT = I.lookupGT
set_lookupIndex = I.lookupIndex
set_lookupLE = I.lookupLE
set_lookupLT = I.lookupLT
set_map = I.map
set_mapMonotonic = I.mapMonotonic
set_maxView = I.maxView
set_member = I.member
set_minView = I.minView
set_notMember = I.notMember
set_null = I.null
set_partition = I.partition
set_showTree = I.showTree
set_showTreeWith = I.showTreeWith
set_singleton = I.singleton
set_size = I.size
set_split = I.split
set_splitMember = I.splitMember
set_splitRoot = I.splitRoot
set_toAscList = I.toAscList
set_toDescList = I.toDescList
set_toList = I.toList
set_union = I.union
set_unions = I.unions
set_valid = I.valid
