{-# LANGUAGE NoMonomorphismRestriction #-}
module Data.ByteString.Lazy.Char8.AsLbs where
-- generated by rvion/jetpack-gen 

import Data.ByteString.Lazy.Char8 as I

-- ($wfirst) doesn't seem to be exported
-- ($wfirst') doesn't seem to be exported
-- ($wfoldl1') doesn't seem to be exported
-- ($wloop) doesn't seem to be exported
-- ($wloop0) doesn't seem to be exported
-- ($wmapAccumL) doesn't seem to be exported
-- ($wmapAccumR) doesn't seem to be exported

lbs_all =  I.all

lbs_any =  I.any

lbs_appendFile =  I.appendFile
-- (appendFile1) doesn't seem to be exported

lbs_break =  I.break

lbs_concatMap =  I.concatMap

lbs_cons =  I.cons

lbs_cons' =  I.cons'

lbs_count =  I.count

lbs_dropWhile =  I.dropWhile

lbs_elem =  I.elem

lbs_elemIndex =  I.elemIndex

lbs_elemIndices =  I.elemIndices

lbs_filter =  I.filter

lbs_find =  I.find

lbs_findIndex =  I.findIndex

lbs_findIndices =  I.findIndices

lbs_foldl =  I.foldl

lbs_foldl' =  I.foldl'

lbs_foldl1 =  I.foldl1

lbs_foldl1' =  I.foldl1'

lbs_foldr =  I.foldr

lbs_foldr1 =  I.foldr1

lbs_groupBy =  I.groupBy

lbs_hPutStrLn =  I.hPutStrLn
-- (hPutStrLn1) doesn't seem to be exported
-- (hPutStrLn2) doesn't seem to be exported
-- (hPutStrLn3) doesn't seem to be exported

lbs_head =  I.head

lbs_index =  I.index

lbs_intersperse =  I.intersperse

lbs_iterate =  I.iterate

lbs_last =  I.last

lbs_lines =  I.lines
-- (lines_loop0) doesn't seem to be exported

lbs_map =  I.map

lbs_mapAccumL =  I.mapAccumL

lbs_mapAccumR =  I.mapAccumR

lbs_maximum =  I.maximum

lbs_minimum =  I.minimum

lbs_notElem =  I.notElem

lbs_pack =  I.pack

lbs_putStrLn =  I.putStrLn
-- (putStrLn1) doesn't seem to be exported

lbs_readFile =  I.readFile
-- (readFile1) doesn't seem to be exported

lbs_readInt =  I.readInt

lbs_readInteger =  I.readInteger

lbs_repeat =  I.repeat

lbs_replicate =  I.replicate

lbs_scanl =  I.scanl

lbs_singleton =  I.singleton

lbs_snoc =  I.snoc

lbs_span =  I.span

lbs_split =  I.split

lbs_splitWith =  I.splitWith

lbs_takeWhile =  I.takeWhile

lbs_uncons =  I.uncons

lbs_unfoldr =  I.unfoldr

lbs_unlines =  I.unlines
-- (unlines1) doesn't seem to be exported
-- (unlines_go1) doesn't seem to be exported
-- (unlines_nl) doesn't seem to be exported

lbs_unpack =  I.unpack

lbs_unsnoc =  I.unsnoc

lbs_unwords =  I.unwords

lbs_words =  I.words

lbs_writeFile =  I.writeFile
-- (writeFile1) doesn't seem to be exported

lbs_zip =  I.zip

lbs_zipWith =  I.zipWith
-- (zip_$szip) doesn't seem to be exported
