{-# LANGUAGE NoMonomorphismRestriction #-}
module Data.Text.AsT where
-- generated by rvion/jetpack-gen 

import Data.Text as I

-- ($c==) doesn't seem to be exported
-- ($fBinaryText) doesn't seem to be exported
-- ($fBinaryText1) doesn't seem to be exported
-- ($fBinaryText_$cget) doesn't seem to be exported
-- ($fBinaryText_$cput) doesn't seem to be exported
-- ($fDataText) doesn't seem to be exported
-- ($fDataText1) doesn't seem to be exported
-- ($fDataText10) doesn't seem to be exported
-- ($fDataText11) doesn't seem to be exported
-- ($fDataText12) doesn't seem to be exported
-- ($fDataText13) doesn't seem to be exported
-- ($fDataText14) doesn't seem to be exported
-- ($fDataText15) doesn't seem to be exported
-- ($fDataText16) doesn't seem to be exported
-- ($fDataText17) doesn't seem to be exported
-- ($fDataText2) doesn't seem to be exported
-- ($fDataText3) doesn't seem to be exported
-- ($fDataText4) doesn't seem to be exported
-- ($fDataText5) doesn't seem to be exported
-- ($fDataText6) doesn't seem to be exported
-- ($fDataText7) doesn't seem to be exported
-- ($fDataText8) doesn't seem to be exported
-- ($fDataText9) doesn't seem to be exported
-- ($fDataText_$cdataTypeOf) doesn't seem to be exported
-- ($fDataText_$cgfoldl) doesn't seem to be exported
-- ($fDataText_$cgmapM) doesn't seem to be exported
-- ($fDataText_$cgmapMo) doesn't seem to be exported
-- ($fDataText_$cgmapMp) doesn't seem to be exported
-- ($fDataText_$cgmapQ) doesn't seem to be exported
-- ($fDataText_$cgmapQi) doesn't seem to be exported
-- ($fDataText_$cgmapQl) doesn't seem to be exported
-- ($fDataText_$cgmapQr) doesn't seem to be exported
-- ($fDataText_$cgmapT) doesn't seem to be exported
-- ($fDataText_$cgunfold) doesn't seem to be exported
-- ($fDataText_$ctoConstr) doesn't seem to be exported
-- ($fDataText_$s$dmdataCast1) doesn't seem to be exported
-- ($fDataText_$s$dmdataCast2) doesn't seem to be exported
-- ($fDataText_$s$fData[]) doesn't seem to be exported
-- ($fDataText_$s$fData[]_$cdataCast1) doesn't seem to be exported
-- ($fDataText_$s$fData[]_$cdataCast2) doesn't seem to be exported
-- ($fDataText_$s$fData[]_$cdataTypeOf) doesn't seem to be exported
-- ($fDataText_$s$fData[]_$ctoConstr) doesn't seem to be exported
-- ($fDataText_w1) doesn't seem to be exported
-- ($fDataText_wild) doesn't seem to be exported
-- ($fDataText_wild1) doesn't seem to be exported
-- ($fDataText_ww1) doesn't seem to be exported
-- ($fDataText_ww2) doesn't seem to be exported
-- ($fDataText_ww3) doesn't seem to be exported
-- ($fDataText_ww4) doesn't seem to be exported
-- ($fDataText_ww5) doesn't seem to be exported
-- ($fDataText_ww6) doesn't seem to be exported
-- ($fDataText_z) doesn't seem to be exported
-- ($fEqText) doesn't seem to be exported
-- ($fEqText_$c/=) doesn't seem to be exported
-- ($fIsListText) doesn't seem to be exported
-- ($fIsListText1) doesn't seem to be exported
-- ($fIsListText_$cfromListN) doesn't seem to be exported
-- ($fIsStringText) doesn't seem to be exported
-- ($fMonoidText) doesn't seem to be exported
-- ($fNFDataText) doesn't seem to be exported
-- ($fNFDataText_$crnf) doesn't seem to be exported
-- ($fOrdText) doesn't seem to be exported
-- ($fOrdText_$c<) doesn't seem to be exported
-- ($fOrdText_$c<=) doesn't seem to be exported
-- ($fOrdText_$c>) doesn't seem to be exported
-- ($fOrdText_$c>=) doesn't seem to be exported
-- ($fOrdText_$ccompare) doesn't seem to be exported
-- ($fOrdText_$cmax) doesn't seem to be exported
-- ($fOrdText_$cmin) doesn't seem to be exported
-- ($fReadText) doesn't seem to be exported
-- ($fReadText1) doesn't seem to be exported
-- ($fReadText2) doesn't seem to be exported
-- ($fReadText3) doesn't seem to be exported
-- ($fReadText4) doesn't seem to be exported
-- ($fReadText_$creadList) doesn't seem to be exported
-- ($fReadText_$creadListPrec) doesn't seem to be exported
-- ($fReadText_$creadPrec) doesn't seem to be exported
-- ($fReadText_$creadsPrec) doesn't seem to be exported
-- ($fReadText_go) doesn't seem to be exported
-- ($w$ccompare) doesn't seem to be exported
-- ($w$cgmapQ) doesn't seem to be exported
-- ($w$cgmapQi) doesn't seem to be exported
-- ($w$cgunfold) doesn't seem to be exported
-- ($w$creadsPrec) doesn't seem to be exported
-- ($wa) doesn't seem to be exported
-- ($wcommonPrefixes) doesn't seem to be exported
-- ($wcopy) doesn't seem to be exported
-- ($wdropEnd) doesn't seem to be exported
-- ($wgo) doesn't seem to be exported
-- ($wgroupBy) doesn't seem to be exported
-- ($winits) doesn't seem to be exported
-- ($witerN) doesn't seem to be exported
-- ($witerNEnd) doesn't seem to be exported
-- ($wlines) doesn't seem to be exported
-- ($wreplace) doesn't seem to be exported
-- ($wstripPrefix) doesn't seem to be exported
-- ($wstripSuffix) doesn't seem to be exported
-- ($wtails) doesn't seem to be exported
-- ($wtakeEnd) doesn't seem to be exported
-- (TFCo:R:ItemText) doesn't seem to be exported

t_all =  I.all

t_any =  I.any

t_append =  I.append

t_break =  I.break

t_breakOn =  I.breakOn

t_breakOnAll =  I.breakOnAll

t_breakOnEnd =  I.breakOnEnd

t_center =  I.center

t_chunksOf =  I.chunksOf

t_commonPrefixes =  I.commonPrefixes

t_compareLength =  I.compareLength

t_concat =  I.concat
-- (concat1) doesn't seem to be exported

t_concatMap =  I.concatMap

t_cons =  I.cons

t_copy =  I.copy

t_count =  I.count
-- (count1) doesn't seem to be exported
-- (countChar) doesn't seem to be exported

t_drop =  I.drop

t_dropAround =  I.dropAround

t_dropEnd =  I.dropEnd

t_dropWhile =  I.dropWhile

t_dropWhileEnd =  I.dropWhileEnd
-- (emptyError) doesn't seem to be exported

t_filter =  I.filter

t_find =  I.find

t_findIndex =  I.findIndex

t_foldl =  I.foldl

t_foldl' =  I.foldl'

t_foldl1 =  I.foldl1

t_foldl1' =  I.foldl1'

t_foldr =  I.foldr

t_foldr1 =  I.foldr1

t_group =  I.group

t_groupBy =  I.groupBy

t_head =  I.head

t_index =  I.index

t_init =  I.init

t_inits =  I.inits

t_intercalate =  I.intercalate

t_intersperse =  I.intersperse

t_isInfixOf =  I.isInfixOf

t_isPrefixOf =  I.isPrefixOf

t_isSuffixOf =  I.isSuffixOf
-- (iterN) doesn't seem to be exported

t_justifyLeft =  I.justifyLeft

t_justifyRight =  I.justifyRight

t_last =  I.last

t_length =  I.length

t_lines =  I.lines

t_map =  I.map

t_mapAccumL =  I.mapAccumL

t_mapAccumR =  I.mapAccumR

t_maximum =  I.maximum

t_minimum =  I.minimum

t_null =  I.null

t_pack =  I.pack
-- (packConstr) doesn't seem to be exported

t_partition =  I.partition

t_replace =  I.replace

t_replicate =  I.replicate
-- (replicateChar) doesn't seem to be exported

t_reverse =  I.reverse

t_scanl =  I.scanl

t_scanl1 =  I.scanl1

t_scanr =  I.scanr

t_scanr1 =  I.scanr1
-- (second) doesn't seem to be exported

t_snoc =  I.snoc

t_span =  I.span

t_split =  I.split

t_splitAt =  I.splitAt

t_splitOn =  I.splitOn

t_strip =  I.strip

t_stripEnd =  I.stripEnd

t_stripPrefix =  I.stripPrefix

t_stripStart =  I.stripStart

t_stripSuffix =  I.stripSuffix

t_tail =  I.tail

t_tails =  I.tails

t_take =  I.take

t_takeEnd =  I.takeEnd

t_takeWhile =  I.takeWhile
-- (textDataType) doesn't seem to be exported

t_toCaseFold =  I.toCaseFold

t_toLower =  I.toLower

t_toTitle =  I.toTitle

t_toUpper =  I.toUpper

t_transpose =  I.transpose

t_uncons =  I.uncons

t_unfoldr =  I.unfoldr

t_unfoldrN =  I.unfoldrN

t_unlines =  I.unlines

t_unwords =  I.unwords

t_words =  I.words

t_zip =  I.zip

t_zipWith =  I.zipWith
