module Options.Applicative.Builder.Completer.AsOpt
  ( module Options.Applicative.Builder.Completer.AsOpt
  ) where
-- generated by https://github.com/rvion/ride/tree/master/jetpack-gen

import qualified Options.Applicative.Builder.Completer as I


-- opt_bashCompleter :: String -> Completer
opt_bashCompleter = I.bashCompleter

-- opt_listCompleter :: [String] -> Completer
opt_listCompleter = I.listCompleter

-- opt_listIOCompleter :: IO [String] -> Completer
opt_listIOCompleter = I.listIOCompleter

-- opt_mkCompleter :: (String -> IO [String]) -> Completer
opt_mkCompleter = I.mkCompleter

type OptCompleter  = I.Completer
