module System.Environment.AsEnv where
-- generated by https://github.com/rvion/ride/tree/master/jetpack-gen

import qualified System.Environment as I


-- env_getArgs :: IO [String]
env_getArgs = I.getArgs

-- env_getEnv :: String -> IO String
env_getEnv = I.getEnv

-- env_getEnvironment :: IO [(String, String)]
env_getEnvironment = I.getEnvironment

-- env_getProgName :: IO String
env_getProgName = I.getProgName

-- env_lookupEnv :: String -> IO (Maybe String)
env_lookupEnv = I.lookupEnv

-- env_setEnv :: String -> String -> IO ()
env_setEnv = I.setEnv

-- env_unsetEnv :: String -> IO ()
env_unsetEnv = I.unsetEnv

-- env_withArgs :: forall a. [String] -> IO a -> IO a
env_withArgs = I.withArgs

-- env_withProgName :: forall a. String -> IO a -> IO a
env_withProgName = I.withProgName

-- env_getExecutablePath :: IO FilePath
env_getExecutablePath = I.getExecutablePath
