module ReexportDemo.AsDemo where
-- generated by rvion/jetpack-gen 

import ReexportDemo as I

type DemoEither a b = I.Either a b
type DemoAcc a b = I.Acc a b
type DemoFoo  = I.Foo 
type DemoThisIsAType  = I.ThisIsAType 
type DemoYo a b = I.Yo a b
