module Control.Monad.Trans.Class.AsTrans
  ( -- unqualified class re-export
  I.MonadTrans(I.lift)
  , module Control.Monad.Trans.Class.AsTrans
  ) where
-- generated by https://github.com/rvion/ride/tree/master/jetpack-gen

import qualified Control.Monad.Trans.Class as I

