module Options.Applicative.Common.AsOpt where
-- generated by https://github.com/rvion/ride/tree/master/jetpack-gen

import qualified Options.Applicative.Common as I

-- opt_evalParser :: forall a. Parser a -> Maybe a
opt_evalParser = I.evalParser

-- opt_liftOpt :: forall a. Option a -> Parser a
opt_liftOpt = I.liftOpt

-- opt_mapParser :: forall a b. (forall x. OptHelpInfo -> Option x -> b) -> Parser a -> [b]
opt_mapParser = I.mapParser

-- opt_optionNames :: forall a. OptReader a -> [OptName]
opt_optionNames = I.optionNames

-- opt_runParser :: forall a (m :: * -> *). MonadP m => ArgPolicy -> Parser a -> Args -> m (a, Args)
opt_runParser = I.runParser

-- opt_runParserFully :: forall a (m :: * -> *). MonadP m => ArgPolicy -> Parser a -> Args -> m a
opt_runParserFully = I.runParserFully

-- opt_runParserInfo :: forall a (m :: * -> *). MonadP m => ParserInfo a -> Args -> m a
opt_runParserInfo = I.runParserInfo

-- opt_showOption :: OptName -> String
opt_showOption = I.showOption

-- opt_treeMapParser :: forall a b. (forall x. OptHelpInfo -> Option x -> b) -> Parser a -> OptTree b
opt_treeMapParser = I.treeMapParser

type OptParser a = I.Parser a
type OptParserInfo a = I.ParserInfo a
opt__mkParserInfo =  I.ParserInfo-- constructor
pattern OptParserInfo a b c d e f g <-  I.ParserInfo a b c d e f g
type OptParserPrefs  = I.ParserPrefs
opt__mkParserPrefs =  I.ParserPrefs-- constructor
pattern OptParserPrefs a b c d e <-  I.ParserPrefs a b c d e
