{-# LANGUAGE NoMonomorphismRestriction #-}
module Data.Text.IO.AsT where
-- generated by rvion/jetpack-gen 

import Data.Text.IO as I


t_appendFile =  I.appendFile
-- (appendFile1) doesn't seem to be exported
-- (appendFile2) doesn't seem to be exported

t_getContents =  I.getContents
-- (getContents1) doesn't seem to be exported
-- (getContents2) doesn't seem to be exported

t_getLine =  I.getLine
-- (getLine1) doesn't seem to be exported

t_hGetChunk =  I.hGetChunk
-- (hGetChunk1) doesn't seem to be exported
-- (hGetChunk2) doesn't seem to be exported
-- (hGetChunk3) doesn't seem to be exported
-- (hGetChunk4) doesn't seem to be exported

t_hGetContents =  I.hGetContents

t_hGetLine =  I.hGetLine
-- (hGetLine1) doesn't seem to be exported

t_hPutStr =  I.hPutStr

t_hPutStrLn =  I.hPutStrLn
-- (hPutStrLn1) doesn't seem to be exported

t_interact =  I.interact
-- (interact1) doesn't seem to be exported

t_putStr =  I.putStr
-- (putStr1) doesn't seem to be exported

t_putStrLn =  I.putStrLn
-- (putStrLn1) doesn't seem to be exported

t_readFile =  I.readFile
-- (readFile1) doesn't seem to be exported

t_writeFile =  I.writeFile
-- (writeFile1) doesn't seem to be exported
