-- generated by rvion/jetpack-gen 
module AsLt where
import Data.Text.Lazy.Encoding

-- ($wa) doesn't seem to be exported

lt_decodeASCII :: ByteString -> Text
lt_decodeASCII =  T.decodeASCII

lt_decodeLatin1 :: ByteString -> Text
lt_decodeLatin1 =  T.decodeLatin1
-- (decodeLatin1_go) doesn't seem to be exported

lt_decodeUtf16BE :: ByteString -> Text
lt_decodeUtf16BE =  T.decodeUtf16BE

lt_decodeUtf16BEWith :: OnDecodeError -> ByteString -> Text
lt_decodeUtf16BEWith =  T.decodeUtf16BEWith

lt_decodeUtf16LE :: ByteString -> Text
lt_decodeUtf16LE =  T.decodeUtf16LE

lt_decodeUtf16LEWith :: OnDecodeError -> ByteString -> Text
lt_decodeUtf16LEWith =  T.decodeUtf16LEWith

lt_decodeUtf32BE :: ByteString -> Text
lt_decodeUtf32BE =  T.decodeUtf32BE

lt_decodeUtf32BEWith :: OnDecodeError -> ByteString -> Text
lt_decodeUtf32BEWith =  T.decodeUtf32BEWith

lt_decodeUtf32LE :: ByteString -> Text
lt_decodeUtf32LE =  T.decodeUtf32LE

lt_decodeUtf32LEWith :: OnDecodeError -> ByteString -> Text
lt_decodeUtf32LEWith =  T.decodeUtf32LEWith

lt_decodeUtf8 :: ByteString -> Text
lt_decodeUtf8 =  T.decodeUtf8

lt_decodeUtf8' :: ByteString -> Either UnicodeException Text
lt_decodeUtf8' =  T.decodeUtf8'

lt_decodeUtf8With :: OnDecodeError -> ByteString -> Text
lt_decodeUtf8With =  T.decodeUtf8With
-- (decodeUtf8With_desc) doesn't seem to be exported

lt_encodeUtf16BE :: Text -> ByteString
lt_encodeUtf16BE =  T.encodeUtf16BE

lt_encodeUtf16LE :: Text -> ByteString
lt_encodeUtf16LE =  T.encodeUtf16LE

lt_encodeUtf32BE :: Text -> ByteString
lt_encodeUtf32BE =  T.encodeUtf32BE

lt_encodeUtf32LE :: Text -> ByteString
lt_encodeUtf32LE =  T.encodeUtf32LE

lt_encodeUtf8 :: Text -> ByteString
lt_encodeUtf8 =  T.encodeUtf8

lt_encodeUtf8Builder :: Text -> Builder
lt_encodeUtf8Builder =  T.encodeUtf8Builder
-- (encodeUtf8Builder1) doesn't seem to be exported
-- (encodeUtf8Builder2) doesn't seem to be exported

lt_encodeUtf8BuilderEscaped :: BoundedPrim Word8 -> Text -> Builder
lt_encodeUtf8BuilderEscaped =  T.encodeUtf8BuilderEscaped
-- (encodeUtf8_$sa) doesn't seem to be exported
-- (encodeUtf8_go) doesn't seem to be exported
