{-# LANGUAGE NoMonomorphismRestriction #-}

module Data.Text.Lazy.Encoding.AsLt where
-- generated by rvion/jetpack-gen 

import Data.Text.Lazy.Encoding as I

lt_decodeASCII = I.decodeASCII
lt_decodeLatin1 = I.decodeLatin1
lt_decodeUtf16BE = I.decodeUtf16BE
lt_decodeUtf16BEWith = I.decodeUtf16BEWith
lt_decodeUtf16LE = I.decodeUtf16LE
lt_decodeUtf16LEWith = I.decodeUtf16LEWith
lt_decodeUtf32BE = I.decodeUtf32BE
lt_decodeUtf32BEWith = I.decodeUtf32BEWith
lt_decodeUtf32LE = I.decodeUtf32LE
lt_decodeUtf32LEWith = I.decodeUtf32LEWith
lt_decodeUtf8 = I.decodeUtf8
lt_decodeUtf8' = I.decodeUtf8'
lt_decodeUtf8With = I.decodeUtf8With
lt_encodeUtf16BE = I.encodeUtf16BE
lt_encodeUtf16LE = I.encodeUtf16LE
lt_encodeUtf32BE = I.encodeUtf32BE
lt_encodeUtf32LE = I.encodeUtf32LE
lt_encodeUtf8 = I.encodeUtf8
lt_encodeUtf8Builder = I.encodeUtf8Builder
lt_encodeUtf8BuilderEscaped = I.encodeUtf8BuilderEscaped
