module Codec.Compression.GZip.AsGzip where
-- generated by https://github.com/rvion/ride/tree/master/jetpack-gen

import qualified Codec.Compression.GZip as I

-- gzip_compress :: ByteString -> ByteString
gzip_compress = I.compress

-- gzip_compressWith :: CompressParams -> ByteString -> ByteString
gzip_compressWith = I.compressWith

-- gzip_decompress :: ByteString -> ByteString
gzip_decompress = I.decompress

-- gzip_decompressWith :: DecompressParams -> ByteString -> ByteString
gzip_decompressWith = I.decompressWith

-- gzip_defaultCompressParams :: CompressParams
gzip_defaultCompressParams = I.defaultCompressParams

-- gzip_defaultDecompressParams :: DecompressParams
gzip_defaultDecompressParams = I.defaultDecompressParams

-- gzip_bestCompression :: CompressionLevel
gzip_bestCompression = I.bestCompression

-- gzip_bestSpeed :: CompressionLevel
gzip_bestSpeed = I.bestSpeed

-- gzip_compressionLevel :: Int -> CompressionLevel
gzip_compressionLevel = I.compressionLevel

-- gzip_defaultCompression :: CompressionLevel
gzip_defaultCompression = I.defaultCompression

-- gzip_defaultMemoryLevel :: MemoryLevel
gzip_defaultMemoryLevel = I.defaultMemoryLevel

-- gzip_defaultStrategy :: CompressionStrategy
gzip_defaultStrategy = I.defaultStrategy

-- gzip_defaultWindowBits :: WindowBits
gzip_defaultWindowBits = I.defaultWindowBits

-- gzip_deflateMethod :: Method
gzip_deflateMethod = I.deflateMethod

-- gzip_filteredStrategy :: CompressionStrategy
gzip_filteredStrategy = I.filteredStrategy

-- gzip_huffmanOnlyStrategy :: CompressionStrategy
gzip_huffmanOnlyStrategy = I.huffmanOnlyStrategy

-- gzip_maxMemoryLevel :: MemoryLevel
gzip_maxMemoryLevel = I.maxMemoryLevel

-- gzip_memoryLevel :: Int -> MemoryLevel
gzip_memoryLevel = I.memoryLevel

-- gzip_minMemoryLevel :: MemoryLevel
gzip_minMemoryLevel = I.minMemoryLevel

-- gzip_noCompression :: CompressionLevel
gzip_noCompression = I.noCompression

-- gzip_windowBits :: Int -> WindowBits
gzip_windowBits = I.windowBits

type GzipCompressParams  = I.CompressParams
gzip_mk'CompressParams =  I.CompressParams-- constructor
pattern GzipCompressParams a b c d e f g <-  I.CompressParams a b c d e f g
type GzipDecompressParams  = I.DecompressParams
gzip_mk'DecompressParams =  I.DecompressParams-- constructor
pattern GzipDecompressParams a b c <-  I.DecompressParams a b c
type GzipCompressionLevel  = I.CompressionLevel
gzip_mk'DefaultCompression =  I.DefaultCompression-- constructor
pattern GzipDefaultCompression  <-  I.DefaultCompression 
gzip_mk'NoCompression =  I.NoCompression-- constructor
pattern GzipNoCompression  <-  I.NoCompression 
gzip_mk'BestSpeed =  I.BestSpeed-- constructor
pattern GzipBestSpeed  <-  I.BestSpeed 
gzip_mk'BestCompression =  I.BestCompression-- constructor
pattern GzipBestCompression  <-  I.BestCompression 
gzip_mk'CompressionLevel =  I.CompressionLevel-- constructor
pattern GzipCompressionLevel a <-  I.CompressionLevel a
type GzipCompressionStrategy  = I.CompressionStrategy
gzip_mk'DefaultStrategy =  I.DefaultStrategy-- constructor
pattern GzipDefaultStrategy  <-  I.DefaultStrategy 
gzip_mk'Filtered =  I.Filtered-- constructor
pattern GzipFiltered  <-  I.Filtered 
gzip_mk'HuffmanOnly =  I.HuffmanOnly-- constructor
pattern GzipHuffmanOnly  <-  I.HuffmanOnly 
type GzipMemoryLevel  = I.MemoryLevel
gzip_mk'DefaultMemoryLevel =  I.DefaultMemoryLevel-- constructor
pattern GzipDefaultMemoryLevel  <-  I.DefaultMemoryLevel 
gzip_mk'MinMemoryLevel =  I.MinMemoryLevel-- constructor
pattern GzipMinMemoryLevel  <-  I.MinMemoryLevel 
gzip_mk'MaxMemoryLevel =  I.MaxMemoryLevel-- constructor
pattern GzipMaxMemoryLevel  <-  I.MaxMemoryLevel 
gzip_mk'MemoryLevel =  I.MemoryLevel-- constructor
pattern GzipMemoryLevel a <-  I.MemoryLevel a
type GzipMethod  = I.Method
gzip_mk'Deflated =  I.Deflated-- constructor
pattern GzipDeflated  <-  I.Deflated 
type GzipWindowBits  = I.WindowBits
gzip_mk'WindowBits =  I.WindowBits-- constructor
pattern GzipWindowBits a <-  I.WindowBits a
gzip_mk'DefaultWindowBits =  I.DefaultWindowBits-- constructor
pattern GzipDefaultWindowBits  <-  I.DefaultWindowBits 
