module Codec.Compression.GZip.AsGzip where
-- generated by rvion/jetpack-gen 

import Codec.Compression.GZip as I

gzip_compress = I.compress
gzip_compressWith = I.compressWith
gzip_decompress = I.decompress
gzip_decompressWith = I.decompressWith
gzip_defaultCompressParams = I.defaultCompressParams
gzip_defaultDecompressParams = I.defaultDecompressParams
gzip_bestCompression = I.bestCompression
gzip_bestSpeed = I.bestSpeed
gzip_compressionLevel = I.compressionLevel
gzip_defaultCompression = I.defaultCompression
gzip_defaultMemoryLevel = I.defaultMemoryLevel
gzip_defaultStrategy = I.defaultStrategy
gzip_defaultWindowBits = I.defaultWindowBits
gzip_deflateMethod = I.deflateMethod
gzip_filteredStrategy = I.filteredStrategy
gzip_huffmanOnlyStrategy = I.huffmanOnlyStrategy
gzip_maxMemoryLevel = I.maxMemoryLevel
gzip_memoryLevel = I.memoryLevel
gzip_minMemoryLevel = I.minMemoryLevel
gzip_noCompression = I.noCompression
gzip_windowBits = I.windowBits
type GzipCompressParams  = I.CompressParams 
type GzipDecompressParams  = I.DecompressParams 
type GzipCompressionLevel  = I.CompressionLevel 
type GzipCompressionStrategy  = I.CompressionStrategy 
type GzipMemoryLevel  = I.MemoryLevel 
type GzipMethod  = I.Method 
type GzipWindowBits  = I.WindowBits 
