{-# LANGUAGE NoMonomorphismRestriction #-}
module Codec.Archive.Tar.AsTar where
-- generated by rvion/jetpack-gen 

import Codec.Archive.Tar as I


tar_append =  I.append
-- (append1) doesn't seem to be exported

tar_create =  I.create
-- (create1) doesn't seem to be exported

tar_extract =  I.extract
-- (extract1) doesn't seem to be exported
