{-# LANGUAGE NoMonomorphismRestriction #-}
module Data.ByteString.Lazy.AsLbs where
-- generated by rvion/jetpack-gen 

import Data.ByteString.Lazy as I

-- ($wa) doesn't seem to be exported
-- ($wa1) doesn't seem to be exported
-- ($wa2) doesn't seem to be exported
-- ($wbreak) doesn't seem to be exported
-- ($wcount) doesn't seem to be exported
-- ($wdrop') doesn't seem to be exported
-- ($wfoldl1') doesn't seem to be exported
-- ($wgo) doesn't seem to be exported
-- ($wgo1) doesn't seem to be exported
-- ($windex') doesn't seem to be exported
-- ($wmapAccumL) doesn't seem to be exported
-- ($wmapAccumR) doesn't seem to be exported
-- ($wpartition) doesn't seem to be exported
-- ($wreplicate) doesn't seem to be exported
-- ($wsplitAt') doesn't seem to be exported
-- ($wtails) doesn't seem to be exported
-- ($wtake') doesn't seem to be exported
-- ($wto) doesn't seem to be exported

lbs_all =  I.all

lbs_any =  I.any

lbs_append =  I.append

lbs_appendFile =  I.appendFile
-- (appendFile1) doesn't seem to be exported
-- (appendFile2) doesn't seem to be exported

lbs_break =  I.break
-- (break1) doesn't seem to be exported

lbs_concat =  I.concat

lbs_concatMap =  I.concatMap

lbs_cons =  I.cons

lbs_cons' =  I.cons'

lbs_copy =  I.copy
-- (copy_go1) doesn't seem to be exported

lbs_count =  I.count

lbs_cycle =  I.cycle
-- (cycle1) doesn't seem to be exported

lbs_drop =  I.drop

lbs_dropWhile =  I.dropWhile
-- (drop_drop') doesn't seem to be exported

lbs_elem =  I.elem

lbs_elemIndex =  I.elemIndex

lbs_elemIndexEnd =  I.elemIndexEnd

lbs_elemIndices =  I.elemIndices

lbs_empty =  I.empty
-- (errorEmptyList) doesn't seem to be exported

lbs_filter =  I.filter

lbs_find =  I.find

lbs_findIndex =  I.findIndex

lbs_findIndices =  I.findIndices

lbs_foldl =  I.foldl

lbs_foldl' =  I.foldl'

lbs_foldl1 =  I.foldl1

lbs_foldl1' =  I.foldl1'
-- (foldl1'1) doesn't seem to be exported
-- (foldl2) doesn't seem to be exported

lbs_foldr =  I.foldr

lbs_foldr1 =  I.foldr1
-- (foldr2) doesn't seem to be exported
-- (foldr3) doesn't seem to be exported

lbs_fromChunks =  I.fromChunks
-- (fromChunks_go) doesn't seem to be exported

lbs_fromStrict =  I.fromStrict

lbs_getContents =  I.getContents
-- (getContents1) doesn't seem to be exported
-- (getContents2) doesn't seem to be exported

lbs_group =  I.group

lbs_groupBy =  I.groupBy
-- (group_$s$wto) doesn't seem to be exported
-- (group_$sgroup) doesn't seem to be exported

lbs_hGet =  I.hGet
-- (hGet1) doesn't seem to be exported
-- (hGet2) doesn't seem to be exported

lbs_hGetContents =  I.hGetContents

lbs_hGetNonBlocking =  I.hGetNonBlocking
-- (hGetNonBlocking1) doesn't seem to be exported
-- (hGetNonBlocking2) doesn't seem to be exported

lbs_hPut =  I.hPut

lbs_hPutNonBlocking =  I.hPutNonBlocking
-- (hPutNonBlocking1) doesn't seem to be exported

lbs_hPutStr =  I.hPutStr

lbs_head =  I.head

lbs_index =  I.index
-- (index1) doesn't seem to be exported

lbs_init =  I.init
-- (init1) doesn't seem to be exported
-- (init_go) doesn't seem to be exported

lbs_inits =  I.inits
-- (inits_inits') doesn't seem to be exported

lbs_interact =  I.interact
-- (interact1) doesn't seem to be exported

lbs_intercalate =  I.intercalate

lbs_intersperse =  I.intersperse

lbs_isPrefixOf =  I.isPrefixOf
-- (isPrefixOf_$sisPrefixOf) doesn't seem to be exported
-- (isPrefixOf_$sisPrefixOf1) doesn't seem to be exported

lbs_isSuffixOf =  I.isSuffixOf

lbs_iterate =  I.iterate

lbs_last =  I.last
-- (last1) doesn't seem to be exported
-- (last_$s$wgo) doesn't seem to be exported
-- (last_go) doesn't seem to be exported

lbs_length =  I.length

lbs_map =  I.map

lbs_mapAccumL =  I.mapAccumL

lbs_mapAccumR =  I.mapAccumR

lbs_maximum =  I.maximum

lbs_minimum =  I.minimum

lbs_notElem =  I.notElem

lbs_null =  I.null

lbs_pack =  I.pack

lbs_partition =  I.partition

lbs_putStr =  I.putStr
-- (putStr1) doesn't seem to be exported

lbs_putStrLn =  I.putStrLn
-- (putStrLn1) doesn't seem to be exported
-- (putStrLn2) doesn't seem to be exported
-- (putStrLn3) doesn't seem to be exported
-- (putStrLn4) doesn't seem to be exported

lbs_readFile =  I.readFile
-- (readFile1) doesn't seem to be exported

lbs_repeat =  I.repeat

lbs_replicate =  I.replicate
-- (revChunks) doesn't seem to be exported

lbs_reverse =  I.reverse

lbs_scanl =  I.scanl

lbs_singleton =  I.singleton

lbs_snoc =  I.snoc

lbs_span =  I.span

lbs_split =  I.split

lbs_splitAt =  I.splitAt
-- (splitAt_splitAt') doesn't seem to be exported

lbs_splitWith =  I.splitWith
-- (split_$sgo) doesn't seem to be exported
-- (split_go) doesn't seem to be exported

lbs_tail =  I.tail

lbs_tails =  I.tails
-- (tails_$s$wtails) doesn't seem to be exported

lbs_take =  I.take

lbs_takeWhile =  I.takeWhile
-- (take_take') doesn't seem to be exported

lbs_toChunks =  I.toChunks
-- (toChunks_$sgo1) doesn't seem to be exported
-- (toChunks_go1) doesn't seem to be exported

lbs_toStrict =  I.toStrict
-- (toStrict1) doesn't seem to be exported
-- (toStrict_$s$wa) doesn't seem to be exported

lbs_transpose =  I.transpose
-- (transpose1) doesn't seem to be exported

lbs_uncons =  I.uncons

lbs_unfoldr =  I.unfoldr
-- (unfoldr1) doesn't seem to be exported

lbs_unpack =  I.unpack

lbs_unsnoc =  I.unsnoc

lbs_unzip =  I.unzip

lbs_writeFile =  I.writeFile
-- (writeFile1) doesn't seem to be exported

lbs_zip =  I.zip

lbs_zipWith =  I.zipWith
