{-# LANGUAGE NoMonomorphismRestriction #-}

module Data.Conduit.List.AsCl where
-- generated by rvion/jetpack-gen 

import Data.Conduit.List as I


cl_catMaybes =  I.catMaybes

cl_concat =  I.concat

cl_concatMap =  I.concatMap

cl_concatMapAccum =  I.concatMapAccum

cl_concatMapAccumM =  I.concatMapAccumM

cl_concatMapM =  I.concatMapM

cl_consume =  I.consume

cl_drop =  I.drop

cl_enumFromTo =  I.enumFromTo

cl_filter =  I.filter

cl_fold =  I.fold

cl_foldM =  I.foldM

cl_foldMap =  I.foldMap

cl_foldMapM =  I.foldMapM

cl_groupBy =  I.groupBy

cl_groupOn1 =  I.groupOn1

cl_head =  I.head

cl_isolate =  I.isolate

cl_iterM =  I.iterM

cl_iterate =  I.iterate

cl_map =  I.map

cl_mapAccum =  I.mapAccum

cl_mapAccumM =  I.mapAccumM

cl_mapFoldable =  I.mapFoldable

cl_mapFoldableM =  I.mapFoldableM

cl_mapM =  I.mapM

cl_mapM_ =  I.mapM_

cl_mapMaybe =  I.mapMaybe

cl_mapMaybeM =  I.mapMaybeM

cl_peek =  I.peek

cl_replicate =  I.replicate

cl_replicateM =  I.replicateM

cl_scan =  I.scan

cl_scanM =  I.scanM

cl_scanl =  I.scanl

cl_scanlM =  I.scanlM

cl_sequence =  I.sequence

cl_sinkNull =  I.sinkNull

cl_sourceList =  I.sourceList

cl_sourceNull =  I.sourceNull

cl_take =  I.take

cl_unfold =  I.unfold

cl_unfoldM =  I.unfoldM
