{-# LANGUAGE NoMonomorphismRestriction #-}
module Data.HashMap.Strict.AsHm where
-- generated by rvion/jetpack-gen 

import Data.HashMap.Strict as I

-- ($wupdateOrSnocWith) doesn't seem to be exported
-- ($wupdateWith) doesn't seem to be exported

hm_adjust =  I.adjust

hm_fromList =  I.fromList

hm_fromListWith =  I.fromListWith

hm_insert =  I.insert

hm_insertWith =  I.insertWith

hm_intersectionWith =  I.intersectionWith

hm_map =  I.map

hm_mapWithKey =  I.mapWithKey

hm_singleton =  I.singleton

hm_unionWith =  I.unionWith
-- (unsafeInsertWith) doesn't seem to be exported
-- (updateOrSnocWith) doesn't seem to be exported
-- (updateWith) doesn't seem to be exported
