module Network.WebSockets.AsWs where
-- generated by https://github.com/rvion/ride/tree/master/jetpack-gen

import qualified Network.WebSockets as I

-- ws_runClient :: forall a. String -> Int -> String -> ClientApp a -> IO a
ws_runClient = I.runClient

-- ws_runClientWith :: forall a. String -> Int -> String -> ConnectionOptions -> Headers -> ClientApp a -> IO a
ws_runClientWith = I.runClientWith

-- ws_runClientWithSocket :: forall a. Socket -> String -> String -> ConnectionOptions -> Headers -> ClientApp a -> IO a
ws_runClientWithSocket = I.runClientWithSocket

-- ws_runClientWithStream :: forall a. Stream -> String -> String -> ConnectionOptions -> Headers -> ClientApp a -> IO a
ws_runClientWithStream = I.runClientWithStream

-- ws_acceptRequest :: PendingConnection -> IO Connection
ws_acceptRequest = I.acceptRequest

-- ws_acceptRequestWith :: PendingConnection -> AcceptRequest -> IO Connection
ws_acceptRequestWith = I.acceptRequestWith

-- ws_defaultConnectionOptions :: ConnectionOptions
ws_defaultConnectionOptions = I.defaultConnectionOptions

-- ws_forkPingThread :: Connection -> Int -> IO ()
ws_forkPingThread = I.forkPingThread

-- ws_receive :: Connection -> IO Message
ws_receive = I.receive

-- ws_receiveData :: forall a. WebSocketsData a => Connection -> IO a
ws_receiveData = I.receiveData

-- ws_receiveDataMessage :: Connection -> IO DataMessage
ws_receiveDataMessage = I.receiveDataMessage

-- ws_rejectRequest :: PendingConnection -> ByteString -> IO ()
ws_rejectRequest = I.rejectRequest

-- ws_send :: Connection -> Message -> IO ()
ws_send = I.send

-- ws_sendBinaryData :: forall a. WebSocketsData a => Connection -> a -> IO ()
ws_sendBinaryData = I.sendBinaryData

-- ws_sendClose :: forall a. WebSocketsData a => Connection -> a -> IO ()
ws_sendClose = I.sendClose

-- ws_sendDataMessage :: Connection -> DataMessage -> IO ()
ws_sendDataMessage = I.sendDataMessage

-- ws_sendPing :: forall a. WebSocketsData a => Connection -> a -> IO ()
ws_sendPing = I.sendPing

-- ws_sendTextData :: forall a. WebSocketsData a => Connection -> a -> IO ()
ws_sendTextData = I.sendTextData

-- ws_getRequestSubprotocols :: RequestHead -> [ByteString]
ws_getRequestSubprotocols = I.getRequestSubprotocols

-- ws_makeListenSocket :: String -> Int -> IO Socket
ws_makeListenSocket = I.makeListenSocket

-- ws_makePendingConnection :: Socket -> ConnectionOptions -> IO PendingConnection
ws_makePendingConnection = I.makePendingConnection

-- ws_makePendingConnectionFromStream :: Stream -> ConnectionOptions -> IO PendingConnection
ws_makePendingConnectionFromStream = I.makePendingConnectionFromStream

-- ws_runServer :: String -> Int -> ServerApp -> IO ()
ws_runServer = I.runServer

-- ws_runServerWith :: String -> Int -> ConnectionOptions -> ServerApp -> IO ()
ws_runServerWith = I.runServerWith

type WsClientApp a = I.ClientApp a
type WsAcceptRequest  = I.AcceptRequest
ws_mk'AcceptRequest =  I.AcceptRequest-- constructor
pattern WsAcceptRequest a <-  I.AcceptRequest a
type WsConnection  = I.Connection
type WsConnectionOptions  = I.ConnectionOptions
ws_mk'ConnectionOptions =  I.ConnectionOptions-- constructor
pattern WsConnectionOptions a <-  I.ConnectionOptions a
type WsPendingConnection  = I.PendingConnection
type WsHandshakeException  = I.HandshakeException
ws_mk'NotSupported =  I.NotSupported-- constructor
pattern WsNotSupported  <-  I.NotSupported 
ws_mk'MalformedRequest =  I.MalformedRequest-- constructor
pattern WsMalformedRequest a b <-  I.MalformedRequest a b
ws_mk'MalformedResponse =  I.MalformedResponse-- constructor
pattern WsMalformedResponse a b <-  I.MalformedResponse a b
ws_mk'RequestRejected =  I.RequestRejected-- constructor
pattern WsRequestRejected a b <-  I.RequestRejected a b
ws_mk'OtherHandshakeException =  I.OtherHandshakeException-- constructor
pattern WsOtherHandshakeException a <-  I.OtherHandshakeException a
type WsHeaders  = I.Headers
type WsRequest  = I.Request
ws_mk'Request =  I.Request-- constructor
pattern WsRequest a b <-  I.Request a b
type WsRequestHead  = I.RequestHead
ws_mk'RequestHead =  I.RequestHead-- constructor
pattern WsRequestHead a b c <-  I.RequestHead a b c
type WsResponse  = I.Response
ws_mk'Response =  I.Response-- constructor
pattern WsResponse a b <-  I.Response a b
type WsResponseHead  = I.ResponseHead
ws_mk'ResponseHead =  I.ResponseHead-- constructor
pattern WsResponseHead a b c <-  I.ResponseHead a b c
type WsServerApp  = I.ServerApp
type WsConnectionException  = I.ConnectionException
ws_mk'CloseRequest =  I.CloseRequest-- constructor
pattern WsCloseRequest a b <-  I.CloseRequest a b
ws_mk'ConnectionClosed =  I.ConnectionClosed-- constructor
pattern WsConnectionClosed  <-  I.ConnectionClosed 
ws_mk'ParseException =  I.ParseException-- constructor
pattern WsParseException a <-  I.ParseException a
type WsControlMessage  = I.ControlMessage
ws_mk'Close =  I.Close-- constructor
pattern WsClose a b <-  I.Close a b
ws_mk'Ping =  I.Ping-- constructor
pattern WsPing a <-  I.Ping a
ws_mk'Pong =  I.Pong-- constructor
pattern WsPong a <-  I.Pong a
type WsDataMessage  = I.DataMessage
ws_mk'Text =  I.Text-- constructor
pattern WsText a <-  I.Text a
ws_mk'Binary =  I.Binary-- constructor
pattern WsBinary a <-  I.Binary a
type WsMessage  = I.Message
ws_mk'ControlMessage =  I.ControlMessage-- constructor
pattern WsControlMessage a <-  I.ControlMessage a
ws_mk'DataMessage =  I.DataMessage-- constructor
pattern WsDataMessage a <-  I.DataMessage a
-- ws_fromLazyByteString :: ByteString -> a
ws_fromLazyByteString = I.fromLazyByteString

-- ws_toLazyByteString :: a -> ByteString
ws_toLazyByteString = I.toLazyByteString

